// Code generated by protoc-gen-go.
// source: c_peer2peer_netmessages.proto
// DO NOT EDIT!

package dota

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type P2P_Messages int32

const (
	P2P_Messages_p2p_TextMessage P2P_Messages = 256
	P2P_Messages_p2p_Voice       P2P_Messages = 257
	P2P_Messages_p2p_Ping        P2P_Messages = 258
)

var P2P_Messages_name = map[int32]string{
	256: "p2p_TextMessage",
	257: "p2p_Voice",
	258: "p2p_Ping",
}
var P2P_Messages_value = map[string]int32{
	"p2p_TextMessage": 256,
	"p2p_Voice":       257,
	"p2p_Ping":        258,
}

func (x P2P_Messages) Enum() *P2P_Messages {
	p := new(P2P_Messages)
	*p = x
	return p
}
func (x P2P_Messages) String() string {
	return proto.EnumName(P2P_Messages_name, int32(x))
}
func (x *P2P_Messages) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(P2P_Messages_value, data, "P2P_Messages")
	if err != nil {
		return err
	}
	*x = P2P_Messages(value)
	return nil
}

type CP2P_Voice_Handler_Flags int32

const (
	CP2P_Voice_Played_Audio CP2P_Voice_Handler_Flags = 1
)

var CP2P_Voice_Handler_Flags_name = map[int32]string{
	1: "Played_Audio",
}
var CP2P_Voice_Handler_Flags_value = map[string]int32{
	"Played_Audio": 1,
}

func (x CP2P_Voice_Handler_Flags) Enum() *CP2P_Voice_Handler_Flags {
	p := new(CP2P_Voice_Handler_Flags)
	*p = x
	return p
}
func (x CP2P_Voice_Handler_Flags) String() string {
	return proto.EnumName(CP2P_Voice_Handler_Flags_name, int32(x))
}
func (x *CP2P_Voice_Handler_Flags) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CP2P_Voice_Handler_Flags_value, data, "CP2P_Voice_Handler_Flags")
	if err != nil {
		return err
	}
	*x = CP2P_Voice_Handler_Flags(value)
	return nil
}

type CP2P_TextMessage struct {
	Text             []byte `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CP2P_TextMessage) Reset()         { *m = CP2P_TextMessage{} }
func (m *CP2P_TextMessage) String() string { return proto.CompactTextString(m) }
func (*CP2P_TextMessage) ProtoMessage()    {}

func (m *CP2P_TextMessage) GetText() []byte {
	if m != nil {
		return m.Text
	}
	return nil
}

type CSteam_Voice_Encoding struct {
	VoiceData        []byte `protobuf:"bytes,1,opt,name=voice_data" json:"voice_data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSteam_Voice_Encoding) Reset()         { *m = CSteam_Voice_Encoding{} }
func (m *CSteam_Voice_Encoding) String() string { return proto.CompactTextString(m) }
func (*CSteam_Voice_Encoding) ProtoMessage()    {}

func (m *CSteam_Voice_Encoding) GetVoiceData() []byte {
	if m != nil {
		return m.VoiceData
	}
	return nil
}

type CP2P_Voice struct {
	Audio            *CMsgVoiceAudio `protobuf:"bytes,1,opt,name=audio" json:"audio,omitempty"`
	BroadcastGroup   *uint32         `protobuf:"varint,2,opt,name=broadcast_group" json:"broadcast_group,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *CP2P_Voice) Reset()         { *m = CP2P_Voice{} }
func (m *CP2P_Voice) String() string { return proto.CompactTextString(m) }
func (*CP2P_Voice) ProtoMessage()    {}

func (m *CP2P_Voice) GetAudio() *CMsgVoiceAudio {
	if m != nil {
		return m.Audio
	}
	return nil
}

func (m *CP2P_Voice) GetBroadcastGroup() uint32 {
	if m != nil && m.BroadcastGroup != nil {
		return *m.BroadcastGroup
	}
	return 0
}

type CP2P_Ping struct {
	SendTime         *uint64 `protobuf:"varint,1,req,name=send_time" json:"send_time,omitempty"`
	IsReply          *bool   `protobuf:"varint,2,req,name=is_reply" json:"is_reply,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CP2P_Ping) Reset()         { *m = CP2P_Ping{} }
func (m *CP2P_Ping) String() string { return proto.CompactTextString(m) }
func (*CP2P_Ping) ProtoMessage()    {}

func (m *CP2P_Ping) GetSendTime() uint64 {
	if m != nil && m.SendTime != nil {
		return *m.SendTime
	}
	return 0
}

func (m *CP2P_Ping) GetIsReply() bool {
	if m != nil && m.IsReply != nil {
		return *m.IsReply
	}
	return false
}

func init() {
	proto.RegisterEnum("dota.P2P_Messages", P2P_Messages_name, P2P_Messages_value)
	proto.RegisterEnum("dota.CP2P_Voice_Handler_Flags", CP2P_Voice_Handler_Flags_name, CP2P_Voice_Handler_Flags_value)
}
