// Code generated by protoc-gen-go.
// source: dota_gcmessages_client_guild.proto
// DO NOT EDIT!

package dota

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CMsgDOTAGuildCreateResponse_EError int32

const (
	CMsgDOTAGuildCreateResponse_UNSPECIFIED             CMsgDOTAGuildCreateResponse_EError = 0
	CMsgDOTAGuildCreateResponse_NAME_EMPTY              CMsgDOTAGuildCreateResponse_EError = 1
	CMsgDOTAGuildCreateResponse_NAME_BAD_CHARACTERS     CMsgDOTAGuildCreateResponse_EError = 2
	CMsgDOTAGuildCreateResponse_NAME_TOO_LONG           CMsgDOTAGuildCreateResponse_EError = 3
	CMsgDOTAGuildCreateResponse_NAME_TAKEN              CMsgDOTAGuildCreateResponse_EError = 4
	CMsgDOTAGuildCreateResponse_TAG_EMPTY               CMsgDOTAGuildCreateResponse_EError = 5
	CMsgDOTAGuildCreateResponse_TAG_BAD_CHARACTERS      CMsgDOTAGuildCreateResponse_EError = 6
	CMsgDOTAGuildCreateResponse_TAG_TOO_LONG            CMsgDOTAGuildCreateResponse_EError = 7
	CMsgDOTAGuildCreateResponse_ACCOUNT_TOO_MANY_GUILDS CMsgDOTAGuildCreateResponse_EError = 8
	CMsgDOTAGuildCreateResponse_LOGO_UPLOAD_FAILED      CMsgDOTAGuildCreateResponse_EError = 9
)

var CMsgDOTAGuildCreateResponse_EError_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "NAME_EMPTY",
	2: "NAME_BAD_CHARACTERS",
	3: "NAME_TOO_LONG",
	4: "NAME_TAKEN",
	5: "TAG_EMPTY",
	6: "TAG_BAD_CHARACTERS",
	7: "TAG_TOO_LONG",
	8: "ACCOUNT_TOO_MANY_GUILDS",
	9: "LOGO_UPLOAD_FAILED",
}
var CMsgDOTAGuildCreateResponse_EError_value = map[string]int32{
	"UNSPECIFIED":             0,
	"NAME_EMPTY":              1,
	"NAME_BAD_CHARACTERS":     2,
	"NAME_TOO_LONG":           3,
	"NAME_TAKEN":              4,
	"TAG_EMPTY":               5,
	"TAG_BAD_CHARACTERS":      6,
	"TAG_TOO_LONG":            7,
	"ACCOUNT_TOO_MANY_GUILDS": 8,
	"LOGO_UPLOAD_FAILED":      9,
}

func (x CMsgDOTAGuildCreateResponse_EError) Enum() *CMsgDOTAGuildCreateResponse_EError {
	p := new(CMsgDOTAGuildCreateResponse_EError)
	*p = x
	return p
}
func (x CMsgDOTAGuildCreateResponse_EError) String() string {
	return proto.EnumName(CMsgDOTAGuildCreateResponse_EError_name, int32(x))
}
func (x *CMsgDOTAGuildCreateResponse_EError) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMsgDOTAGuildCreateResponse_EError_value, data, "CMsgDOTAGuildCreateResponse_EError")
	if err != nil {
		return err
	}
	*x = CMsgDOTAGuildCreateResponse_EError(value)
	return nil
}
func (CMsgDOTAGuildCreateResponse_EError) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor12, []int{4, 0}
}

type CMsgDOTAGuildSetAccountRoleResponse_EResult int32

const (
	CMsgDOTAGuildSetAccountRoleResponse_SUCCESS                       CMsgDOTAGuildSetAccountRoleResponse_EResult = 0
	CMsgDOTAGuildSetAccountRoleResponse_ERROR_UNSPECIFIED             CMsgDOTAGuildSetAccountRoleResponse_EResult = 1
	CMsgDOTAGuildSetAccountRoleResponse_ERROR_NO_PERMISSION           CMsgDOTAGuildSetAccountRoleResponse_EResult = 2
	CMsgDOTAGuildSetAccountRoleResponse_ERROR_NO_OTHER_LEADER         CMsgDOTAGuildSetAccountRoleResponse_EResult = 3
	CMsgDOTAGuildSetAccountRoleResponse_ERROR_ACCOUNT_TOO_MANY_GUILDS CMsgDOTAGuildSetAccountRoleResponse_EResult = 4
	CMsgDOTAGuildSetAccountRoleResponse_ERROR_GUILD_TOO_MANY_MEMBERS  CMsgDOTAGuildSetAccountRoleResponse_EResult = 5
)

var CMsgDOTAGuildSetAccountRoleResponse_EResult_name = map[int32]string{
	0: "SUCCESS",
	1: "ERROR_UNSPECIFIED",
	2: "ERROR_NO_PERMISSION",
	3: "ERROR_NO_OTHER_LEADER",
	4: "ERROR_ACCOUNT_TOO_MANY_GUILDS",
	5: "ERROR_GUILD_TOO_MANY_MEMBERS",
}
var CMsgDOTAGuildSetAccountRoleResponse_EResult_value = map[string]int32{
	"SUCCESS":                       0,
	"ERROR_UNSPECIFIED":             1,
	"ERROR_NO_PERMISSION":           2,
	"ERROR_NO_OTHER_LEADER":         3,
	"ERROR_ACCOUNT_TOO_MANY_GUILDS": 4,
	"ERROR_GUILD_TOO_MANY_MEMBERS":  5,
}

func (x CMsgDOTAGuildSetAccountRoleResponse_EResult) Enum() *CMsgDOTAGuildSetAccountRoleResponse_EResult {
	p := new(CMsgDOTAGuildSetAccountRoleResponse_EResult)
	*p = x
	return p
}
func (x CMsgDOTAGuildSetAccountRoleResponse_EResult) String() string {
	return proto.EnumName(CMsgDOTAGuildSetAccountRoleResponse_EResult_name, int32(x))
}
func (x *CMsgDOTAGuildSetAccountRoleResponse_EResult) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMsgDOTAGuildSetAccountRoleResponse_EResult_value, data, "CMsgDOTAGuildSetAccountRoleResponse_EResult")
	if err != nil {
		return err
	}
	*x = CMsgDOTAGuildSetAccountRoleResponse_EResult(value)
	return nil
}
func (CMsgDOTAGuildSetAccountRoleResponse_EResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor12, []int{6, 0}
}

type CMsgDOTAGuildInviteAccountResponse_EResult int32

const (
	CMsgDOTAGuildInviteAccountResponse_SUCCESS                        CMsgDOTAGuildInviteAccountResponse_EResult = 0
	CMsgDOTAGuildInviteAccountResponse_ERROR_UNSPECIFIED              CMsgDOTAGuildInviteAccountResponse_EResult = 1
	CMsgDOTAGuildInviteAccountResponse_ERROR_NO_PERMISSION            CMsgDOTAGuildInviteAccountResponse_EResult = 2
	CMsgDOTAGuildInviteAccountResponse_ERROR_ACCOUNT_ALREADY_INVITED  CMsgDOTAGuildInviteAccountResponse_EResult = 3
	CMsgDOTAGuildInviteAccountResponse_ERROR_ACCOUNT_ALREADY_IN_GUILD CMsgDOTAGuildInviteAccountResponse_EResult = 4
	CMsgDOTAGuildInviteAccountResponse_ERROR_ACCOUNT_TOO_MANY_INVITES CMsgDOTAGuildInviteAccountResponse_EResult = 5
	CMsgDOTAGuildInviteAccountResponse_ERROR_GUILD_TOO_MANY_INVITES   CMsgDOTAGuildInviteAccountResponse_EResult = 6
	CMsgDOTAGuildInviteAccountResponse_ERROR_ACCOUNT_TOO_MANY_GUILDS  CMsgDOTAGuildInviteAccountResponse_EResult = 7
)

var CMsgDOTAGuildInviteAccountResponse_EResult_name = map[int32]string{
	0: "SUCCESS",
	1: "ERROR_UNSPECIFIED",
	2: "ERROR_NO_PERMISSION",
	3: "ERROR_ACCOUNT_ALREADY_INVITED",
	4: "ERROR_ACCOUNT_ALREADY_IN_GUILD",
	5: "ERROR_ACCOUNT_TOO_MANY_INVITES",
	6: "ERROR_GUILD_TOO_MANY_INVITES",
	7: "ERROR_ACCOUNT_TOO_MANY_GUILDS",
}
var CMsgDOTAGuildInviteAccountResponse_EResult_value = map[string]int32{
	"SUCCESS":                        0,
	"ERROR_UNSPECIFIED":              1,
	"ERROR_NO_PERMISSION":            2,
	"ERROR_ACCOUNT_ALREADY_INVITED":  3,
	"ERROR_ACCOUNT_ALREADY_IN_GUILD": 4,
	"ERROR_ACCOUNT_TOO_MANY_INVITES": 5,
	"ERROR_GUILD_TOO_MANY_INVITES":   6,
	"ERROR_ACCOUNT_TOO_MANY_GUILDS":  7,
}

func (x CMsgDOTAGuildInviteAccountResponse_EResult) Enum() *CMsgDOTAGuildInviteAccountResponse_EResult {
	p := new(CMsgDOTAGuildInviteAccountResponse_EResult)
	*p = x
	return p
}
func (x CMsgDOTAGuildInviteAccountResponse_EResult) String() string {
	return proto.EnumName(CMsgDOTAGuildInviteAccountResponse_EResult_name, int32(x))
}
func (x *CMsgDOTAGuildInviteAccountResponse_EResult) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMsgDOTAGuildInviteAccountResponse_EResult_value, data, "CMsgDOTAGuildInviteAccountResponse_EResult")
	if err != nil {
		return err
	}
	*x = CMsgDOTAGuildInviteAccountResponse_EResult(value)
	return nil
}
func (CMsgDOTAGuildInviteAccountResponse_EResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor12, []int{8, 0}
}

type CMsgDOTAGuildCancelInviteResponse_EResult int32

const (
	CMsgDOTAGuildCancelInviteResponse_SUCCESS             CMsgDOTAGuildCancelInviteResponse_EResult = 0
	CMsgDOTAGuildCancelInviteResponse_ERROR_UNSPECIFIED   CMsgDOTAGuildCancelInviteResponse_EResult = 1
	CMsgDOTAGuildCancelInviteResponse_ERROR_NO_PERMISSION CMsgDOTAGuildCancelInviteResponse_EResult = 2
)

var CMsgDOTAGuildCancelInviteResponse_EResult_name = map[int32]string{
	0: "SUCCESS",
	1: "ERROR_UNSPECIFIED",
	2: "ERROR_NO_PERMISSION",
}
var CMsgDOTAGuildCancelInviteResponse_EResult_value = map[string]int32{
	"SUCCESS":             0,
	"ERROR_UNSPECIFIED":   1,
	"ERROR_NO_PERMISSION": 2,
}

func (x CMsgDOTAGuildCancelInviteResponse_EResult) Enum() *CMsgDOTAGuildCancelInviteResponse_EResult {
	p := new(CMsgDOTAGuildCancelInviteResponse_EResult)
	*p = x
	return p
}
func (x CMsgDOTAGuildCancelInviteResponse_EResult) String() string {
	return proto.EnumName(CMsgDOTAGuildCancelInviteResponse_EResult_name, int32(x))
}
func (x *CMsgDOTAGuildCancelInviteResponse_EResult) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMsgDOTAGuildCancelInviteResponse_EResult_value, data, "CMsgDOTAGuildCancelInviteResponse_EResult")
	if err != nil {
		return err
	}
	*x = CMsgDOTAGuildCancelInviteResponse_EResult(value)
	return nil
}
func (CMsgDOTAGuildCancelInviteResponse_EResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor12, []int{10, 0}
}

type CMsgDOTAGuildUpdateDetailsResponse_EResult int32

const (
	CMsgDOTAGuildUpdateDetailsResponse_SUCCESS             CMsgDOTAGuildUpdateDetailsResponse_EResult = 0
	CMsgDOTAGuildUpdateDetailsResponse_ERROR_UNSPECIFIED   CMsgDOTAGuildUpdateDetailsResponse_EResult = 1
	CMsgDOTAGuildUpdateDetailsResponse_ERROR_NO_PERMISSION CMsgDOTAGuildUpdateDetailsResponse_EResult = 2
)

var CMsgDOTAGuildUpdateDetailsResponse_EResult_name = map[int32]string{
	0: "SUCCESS",
	1: "ERROR_UNSPECIFIED",
	2: "ERROR_NO_PERMISSION",
}
var CMsgDOTAGuildUpdateDetailsResponse_EResult_value = map[string]int32{
	"SUCCESS":             0,
	"ERROR_UNSPECIFIED":   1,
	"ERROR_NO_PERMISSION": 2,
}

func (x CMsgDOTAGuildUpdateDetailsResponse_EResult) Enum() *CMsgDOTAGuildUpdateDetailsResponse_EResult {
	p := new(CMsgDOTAGuildUpdateDetailsResponse_EResult)
	*p = x
	return p
}
func (x CMsgDOTAGuildUpdateDetailsResponse_EResult) String() string {
	return proto.EnumName(CMsgDOTAGuildUpdateDetailsResponse_EResult_name, int32(x))
}
func (x *CMsgDOTAGuildUpdateDetailsResponse_EResult) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMsgDOTAGuildUpdateDetailsResponse_EResult_value, data, "CMsgDOTAGuildUpdateDetailsResponse_EResult")
	if err != nil {
		return err
	}
	*x = CMsgDOTAGuildUpdateDetailsResponse_EResult(value)
	return nil
}
func (CMsgDOTAGuildUpdateDetailsResponse_EResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor12, []int{12, 0}
}

type CMsgDOTAPartySetOpenGuildResponse_EResult int32

const (
	CMsgDOTAPartySetOpenGuildResponse_SUCCESS           CMsgDOTAPartySetOpenGuildResponse_EResult = 0
	CMsgDOTAPartySetOpenGuildResponse_ERROR_UNSPECIFIED CMsgDOTAPartySetOpenGuildResponse_EResult = 1
)

var CMsgDOTAPartySetOpenGuildResponse_EResult_name = map[int32]string{
	0: "SUCCESS",
	1: "ERROR_UNSPECIFIED",
}
var CMsgDOTAPartySetOpenGuildResponse_EResult_value = map[string]int32{
	"SUCCESS":           0,
	"ERROR_UNSPECIFIED": 1,
}

func (x CMsgDOTAPartySetOpenGuildResponse_EResult) Enum() *CMsgDOTAPartySetOpenGuildResponse_EResult {
	p := new(CMsgDOTAPartySetOpenGuildResponse_EResult)
	*p = x
	return p
}
func (x CMsgDOTAPartySetOpenGuildResponse_EResult) String() string {
	return proto.EnumName(CMsgDOTAPartySetOpenGuildResponse_EResult_name, int32(x))
}
func (x *CMsgDOTAPartySetOpenGuildResponse_EResult) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMsgDOTAPartySetOpenGuildResponse_EResult_value, data, "CMsgDOTAPartySetOpenGuildResponse_EResult")
	if err != nil {
		return err
	}
	*x = CMsgDOTAPartySetOpenGuildResponse_EResult(value)
	return nil
}
func (CMsgDOTAPartySetOpenGuildResponse_EResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor12, []int{18, 0}
}

type CMsgDOTAJoinOpenGuildPartyResponse_EResult int32

const (
	CMsgDOTAJoinOpenGuildPartyResponse_SUCCESS           CMsgDOTAJoinOpenGuildPartyResponse_EResult = 0
	CMsgDOTAJoinOpenGuildPartyResponse_ERROR_UNSPECIFIED CMsgDOTAJoinOpenGuildPartyResponse_EResult = 1
)

var CMsgDOTAJoinOpenGuildPartyResponse_EResult_name = map[int32]string{
	0: "SUCCESS",
	1: "ERROR_UNSPECIFIED",
}
var CMsgDOTAJoinOpenGuildPartyResponse_EResult_value = map[string]int32{
	"SUCCESS":           0,
	"ERROR_UNSPECIFIED": 1,
}

func (x CMsgDOTAJoinOpenGuildPartyResponse_EResult) Enum() *CMsgDOTAJoinOpenGuildPartyResponse_EResult {
	p := new(CMsgDOTAJoinOpenGuildPartyResponse_EResult)
	*p = x
	return p
}
func (x CMsgDOTAJoinOpenGuildPartyResponse_EResult) String() string {
	return proto.EnumName(CMsgDOTAJoinOpenGuildPartyResponse_EResult_name, int32(x))
}
func (x *CMsgDOTAJoinOpenGuildPartyResponse_EResult) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMsgDOTAJoinOpenGuildPartyResponse_EResult_value, data, "CMsgDOTAJoinOpenGuildPartyResponse_EResult")
	if err != nil {
		return err
	}
	*x = CMsgDOTAJoinOpenGuildPartyResponse_EResult(value)
	return nil
}
func (CMsgDOTAJoinOpenGuildPartyResponse_EResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor12, []int{20, 0}
}

type CMsgDOTAGuildEditLogoResponse_EResult int32

const (
	CMsgDOTAGuildEditLogoResponse_SUCCESS            CMsgDOTAGuildEditLogoResponse_EResult = 0
	CMsgDOTAGuildEditLogoResponse_NO_PERMISSION      CMsgDOTAGuildEditLogoResponse_EResult = 1
	CMsgDOTAGuildEditLogoResponse_LOGO_UPLOAD_FAILED CMsgDOTAGuildEditLogoResponse_EResult = 2
	CMsgDOTAGuildEditLogoResponse_UNSPECIFIED_ERROR  CMsgDOTAGuildEditLogoResponse_EResult = 3
)

var CMsgDOTAGuildEditLogoResponse_EResult_name = map[int32]string{
	0: "SUCCESS",
	1: "NO_PERMISSION",
	2: "LOGO_UPLOAD_FAILED",
	3: "UNSPECIFIED_ERROR",
}
var CMsgDOTAGuildEditLogoResponse_EResult_value = map[string]int32{
	"SUCCESS":            0,
	"NO_PERMISSION":      1,
	"LOGO_UPLOAD_FAILED": 2,
	"UNSPECIFIED_ERROR":  3,
}

func (x CMsgDOTAGuildEditLogoResponse_EResult) Enum() *CMsgDOTAGuildEditLogoResponse_EResult {
	p := new(CMsgDOTAGuildEditLogoResponse_EResult)
	*p = x
	return p
}
func (x CMsgDOTAGuildEditLogoResponse_EResult) String() string {
	return proto.EnumName(CMsgDOTAGuildEditLogoResponse_EResult_name, int32(x))
}
func (x *CMsgDOTAGuildEditLogoResponse_EResult) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMsgDOTAGuildEditLogoResponse_EResult_value, data, "CMsgDOTAGuildEditLogoResponse_EResult")
	if err != nil {
		return err
	}
	*x = CMsgDOTAGuildEditLogoResponse_EResult(value)
	return nil
}
func (CMsgDOTAGuildEditLogoResponse_EResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor12, []int{26, 0}
}

type CMsgDOTAGuildSDO struct {
	GuildId          *uint32                        `protobuf:"varint,1,opt,name=guild_id" json:"guild_id,omitempty"`
	Name             *string                        `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Tag              *string                        `protobuf:"bytes,3,opt,name=tag" json:"tag,omitempty"`
	TimeCreated      *uint32                        `protobuf:"varint,4,opt,name=time_created" json:"time_created,omitempty"`
	TimeDisbanded    *uint32                        `protobuf:"varint,5,opt,name=time_disbanded" json:"time_disbanded,omitempty"`
	Logo             *uint64                        `protobuf:"varint,6,opt,name=logo" json:"logo,omitempty"`
	BaseLogo         *uint64                        `protobuf:"varint,7,opt,name=base_logo" json:"base_logo,omitempty"`
	BannerLogo       *uint64                        `protobuf:"varint,8,opt,name=banner_logo" json:"banner_logo,omitempty"`
	Members          []*CMsgDOTAGuildSDO_Member     `protobuf:"bytes,9,rep,name=members" json:"members,omitempty"`
	Invitations      []*CMsgDOTAGuildSDO_Invitation `protobuf:"bytes,10,rep,name=invitations" json:"invitations,omitempty"`
	Message          *string                        `protobuf:"bytes,11,opt,name=message" json:"message,omitempty"`
	Incremental      *bool                          `protobuf:"varint,12,opt,name=incremental" json:"incremental,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *CMsgDOTAGuildSDO) Reset()                    { *m = CMsgDOTAGuildSDO{} }
func (m *CMsgDOTAGuildSDO) String() string            { return proto.CompactTextString(m) }
func (*CMsgDOTAGuildSDO) ProtoMessage()               {}
func (*CMsgDOTAGuildSDO) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{0} }

func (m *CMsgDOTAGuildSDO) GetGuildId() uint32 {
	if m != nil && m.GuildId != nil {
		return *m.GuildId
	}
	return 0
}

func (m *CMsgDOTAGuildSDO) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CMsgDOTAGuildSDO) GetTag() string {
	if m != nil && m.Tag != nil {
		return *m.Tag
	}
	return ""
}

func (m *CMsgDOTAGuildSDO) GetTimeCreated() uint32 {
	if m != nil && m.TimeCreated != nil {
		return *m.TimeCreated
	}
	return 0
}

func (m *CMsgDOTAGuildSDO) GetTimeDisbanded() uint32 {
	if m != nil && m.TimeDisbanded != nil {
		return *m.TimeDisbanded
	}
	return 0
}

func (m *CMsgDOTAGuildSDO) GetLogo() uint64 {
	if m != nil && m.Logo != nil {
		return *m.Logo
	}
	return 0
}

func (m *CMsgDOTAGuildSDO) GetBaseLogo() uint64 {
	if m != nil && m.BaseLogo != nil {
		return *m.BaseLogo
	}
	return 0
}

func (m *CMsgDOTAGuildSDO) GetBannerLogo() uint64 {
	if m != nil && m.BannerLogo != nil {
		return *m.BannerLogo
	}
	return 0
}

func (m *CMsgDOTAGuildSDO) GetMembers() []*CMsgDOTAGuildSDO_Member {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *CMsgDOTAGuildSDO) GetInvitations() []*CMsgDOTAGuildSDO_Invitation {
	if m != nil {
		return m.Invitations
	}
	return nil
}

func (m *CMsgDOTAGuildSDO) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *CMsgDOTAGuildSDO) GetIncremental() bool {
	if m != nil && m.Incremental != nil {
		return *m.Incremental
	}
	return false
}

type CMsgDOTAGuildSDO_Member struct {
	AccountId        *uint32 `protobuf:"varint,1,opt,name=account_id" json:"account_id,omitempty"`
	TimeJoined       *uint32 `protobuf:"varint,2,opt,name=time_joined" json:"time_joined,omitempty"`
	Role             *uint32 `protobuf:"varint,3,opt,name=role" json:"role,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgDOTAGuildSDO_Member) Reset()                    { *m = CMsgDOTAGuildSDO_Member{} }
func (m *CMsgDOTAGuildSDO_Member) String() string            { return proto.CompactTextString(m) }
func (*CMsgDOTAGuildSDO_Member) ProtoMessage()               {}
func (*CMsgDOTAGuildSDO_Member) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{0, 0} }

func (m *CMsgDOTAGuildSDO_Member) GetAccountId() uint32 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *CMsgDOTAGuildSDO_Member) GetTimeJoined() uint32 {
	if m != nil && m.TimeJoined != nil {
		return *m.TimeJoined
	}
	return 0
}

func (m *CMsgDOTAGuildSDO_Member) GetRole() uint32 {
	if m != nil && m.Role != nil {
		return *m.Role
	}
	return 0
}

type CMsgDOTAGuildSDO_Invitation struct {
	AccountId        *uint32 `protobuf:"varint,1,opt,name=account_id" json:"account_id,omitempty"`
	TimeSent         *uint32 `protobuf:"varint,2,opt,name=time_sent" json:"time_sent,omitempty"`
	AccountIdSender  *uint32 `protobuf:"varint,3,opt,name=account_id_sender" json:"account_id_sender,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgDOTAGuildSDO_Invitation) Reset()                    { *m = CMsgDOTAGuildSDO_Invitation{} }
func (m *CMsgDOTAGuildSDO_Invitation) String() string            { return proto.CompactTextString(m) }
func (*CMsgDOTAGuildSDO_Invitation) ProtoMessage()               {}
func (*CMsgDOTAGuildSDO_Invitation) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{0, 1} }

func (m *CMsgDOTAGuildSDO_Invitation) GetAccountId() uint32 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *CMsgDOTAGuildSDO_Invitation) GetTimeSent() uint32 {
	if m != nil && m.TimeSent != nil {
		return *m.TimeSent
	}
	return 0
}

func (m *CMsgDOTAGuildSDO_Invitation) GetAccountIdSender() uint32 {
	if m != nil && m.AccountIdSender != nil {
		return *m.AccountIdSender
	}
	return 0
}

type CMsgDOTAGuildAuditSDO struct {
	GuildId          *uint32                        `protobuf:"varint,1,opt,name=guild_id" json:"guild_id,omitempty"`
	Entries          []*CMsgDOTAGuildAuditSDO_Entry `protobuf:"bytes,2,rep,name=entries" json:"entries,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *CMsgDOTAGuildAuditSDO) Reset()                    { *m = CMsgDOTAGuildAuditSDO{} }
func (m *CMsgDOTAGuildAuditSDO) String() string            { return proto.CompactTextString(m) }
func (*CMsgDOTAGuildAuditSDO) ProtoMessage()               {}
func (*CMsgDOTAGuildAuditSDO) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{1} }

func (m *CMsgDOTAGuildAuditSDO) GetGuildId() uint32 {
	if m != nil && m.GuildId != nil {
		return *m.GuildId
	}
	return 0
}

func (m *CMsgDOTAGuildAuditSDO) GetEntries() []*CMsgDOTAGuildAuditSDO_Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type CMsgDOTAGuildAuditSDO_Entry struct {
	EventIndex         *uint32 `protobuf:"varint,1,opt,name=event_index" json:"event_index,omitempty"`
	Timestamp          *uint32 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Action             *uint32 `protobuf:"varint,3,opt,name=action" json:"action,omitempty"`
	AccountIdRequestor *uint32 `protobuf:"varint,4,opt,name=account_id_requestor" json:"account_id_requestor,omitempty"`
	AccountIdTarget    *uint32 `protobuf:"varint,5,opt,name=account_id_target" json:"account_id_target,omitempty"`
	ReferenceDataA     *uint32 `protobuf:"varint,6,opt,name=reference_data_a" json:"reference_data_a,omitempty"`
	ReferenceDataB     *uint32 `protobuf:"varint,7,opt,name=reference_data_b" json:"reference_data_b,omitempty"`
	XXX_unrecognized   []byte  `json:"-"`
}

func (m *CMsgDOTAGuildAuditSDO_Entry) Reset()                    { *m = CMsgDOTAGuildAuditSDO_Entry{} }
func (m *CMsgDOTAGuildAuditSDO_Entry) String() string            { return proto.CompactTextString(m) }
func (*CMsgDOTAGuildAuditSDO_Entry) ProtoMessage()               {}
func (*CMsgDOTAGuildAuditSDO_Entry) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{1, 0} }

func (m *CMsgDOTAGuildAuditSDO_Entry) GetEventIndex() uint32 {
	if m != nil && m.EventIndex != nil {
		return *m.EventIndex
	}
	return 0
}

func (m *CMsgDOTAGuildAuditSDO_Entry) GetTimestamp() uint32 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *CMsgDOTAGuildAuditSDO_Entry) GetAction() uint32 {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return 0
}

func (m *CMsgDOTAGuildAuditSDO_Entry) GetAccountIdRequestor() uint32 {
	if m != nil && m.AccountIdRequestor != nil {
		return *m.AccountIdRequestor
	}
	return 0
}

func (m *CMsgDOTAGuildAuditSDO_Entry) GetAccountIdTarget() uint32 {
	if m != nil && m.AccountIdTarget != nil {
		return *m.AccountIdTarget
	}
	return 0
}

func (m *CMsgDOTAGuildAuditSDO_Entry) GetReferenceDataA() uint32 {
	if m != nil && m.ReferenceDataA != nil {
		return *m.ReferenceDataA
	}
	return 0
}

func (m *CMsgDOTAGuildAuditSDO_Entry) GetReferenceDataB() uint32 {
	if m != nil && m.ReferenceDataB != nil {
		return *m.ReferenceDataB
	}
	return 0
}

type CMsgDOTAAccountGuildMembershipsSDO struct {
	AccountId        *uint32                                          `protobuf:"varint,1,opt,name=account_id" json:"account_id,omitempty"`
	Memberships      []*CMsgDOTAAccountGuildMembershipsSDO_Membership `protobuf:"bytes,2,rep,name=memberships" json:"memberships,omitempty"`
	Invitations      []*CMsgDOTAAccountGuildMembershipsSDO_Invitation `protobuf:"bytes,3,rep,name=invitations" json:"invitations,omitempty"`
	XXX_unrecognized []byte                                           `json:"-"`
}

func (m *CMsgDOTAAccountGuildMembershipsSDO) Reset()         { *m = CMsgDOTAAccountGuildMembershipsSDO{} }
func (m *CMsgDOTAAccountGuildMembershipsSDO) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAAccountGuildMembershipsSDO) ProtoMessage()    {}
func (*CMsgDOTAAccountGuildMembershipsSDO) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{2}
}

func (m *CMsgDOTAAccountGuildMembershipsSDO) GetAccountId() uint32 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *CMsgDOTAAccountGuildMembershipsSDO) GetMemberships() []*CMsgDOTAAccountGuildMembershipsSDO_Membership {
	if m != nil {
		return m.Memberships
	}
	return nil
}

func (m *CMsgDOTAAccountGuildMembershipsSDO) GetInvitations() []*CMsgDOTAAccountGuildMembershipsSDO_Invitation {
	if m != nil {
		return m.Invitations
	}
	return nil
}

type CMsgDOTAAccountGuildMembershipsSDO_Membership struct {
	GuildId          *uint32 `protobuf:"varint,1,opt,name=guild_id" json:"guild_id,omitempty"`
	Role             *uint32 `protobuf:"varint,2,opt,name=role" json:"role,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgDOTAAccountGuildMembershipsSDO_Membership) Reset() {
	*m = CMsgDOTAAccountGuildMembershipsSDO_Membership{}
}
func (m *CMsgDOTAAccountGuildMembershipsSDO_Membership) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgDOTAAccountGuildMembershipsSDO_Membership) ProtoMessage() {}
func (*CMsgDOTAAccountGuildMembershipsSDO_Membership) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{2, 0}
}

func (m *CMsgDOTAAccountGuildMembershipsSDO_Membership) GetGuildId() uint32 {
	if m != nil && m.GuildId != nil {
		return *m.GuildId
	}
	return 0
}

func (m *CMsgDOTAAccountGuildMembershipsSDO_Membership) GetRole() uint32 {
	if m != nil && m.Role != nil {
		return *m.Role
	}
	return 0
}

type CMsgDOTAAccountGuildMembershipsSDO_Invitation struct {
	GuildId          *uint32 `protobuf:"varint,1,opt,name=guild_id" json:"guild_id,omitempty"`
	TimeSent         *uint32 `protobuf:"varint,2,opt,name=time_sent" json:"time_sent,omitempty"`
	AccountIdSender  *uint32 `protobuf:"varint,3,opt,name=account_id_sender" json:"account_id_sender,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgDOTAAccountGuildMembershipsSDO_Invitation) Reset() {
	*m = CMsgDOTAAccountGuildMembershipsSDO_Invitation{}
}
func (m *CMsgDOTAAccountGuildMembershipsSDO_Invitation) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgDOTAAccountGuildMembershipsSDO_Invitation) ProtoMessage() {}
func (*CMsgDOTAAccountGuildMembershipsSDO_Invitation) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{2, 1}
}

func (m *CMsgDOTAAccountGuildMembershipsSDO_Invitation) GetGuildId() uint32 {
	if m != nil && m.GuildId != nil {
		return *m.GuildId
	}
	return 0
}

func (m *CMsgDOTAAccountGuildMembershipsSDO_Invitation) GetTimeSent() uint32 {
	if m != nil && m.TimeSent != nil {
		return *m.TimeSent
	}
	return 0
}

func (m *CMsgDOTAAccountGuildMembershipsSDO_Invitation) GetAccountIdSender() uint32 {
	if m != nil && m.AccountIdSender != nil {
		return *m.AccountIdSender
	}
	return 0
}

type CMsgDOTAGuildCreateRequest struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Tag              *string `protobuf:"bytes,2,opt,name=tag" json:"tag,omitempty"`
	Logo             *uint64 `protobuf:"varint,3,opt,name=logo" json:"logo,omitempty"`
	BaseLogo         *uint64 `protobuf:"varint,4,opt,name=base_logo" json:"base_logo,omitempty"`
	BannerLogo       *uint64 `protobuf:"varint,5,opt,name=banner_logo" json:"banner_logo,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgDOTAGuildCreateRequest) Reset()                    { *m = CMsgDOTAGuildCreateRequest{} }
func (m *CMsgDOTAGuildCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CMsgDOTAGuildCreateRequest) ProtoMessage()               {}
func (*CMsgDOTAGuildCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{3} }

func (m *CMsgDOTAGuildCreateRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CMsgDOTAGuildCreateRequest) GetTag() string {
	if m != nil && m.Tag != nil {
		return *m.Tag
	}
	return ""
}

func (m *CMsgDOTAGuildCreateRequest) GetLogo() uint64 {
	if m != nil && m.Logo != nil {
		return *m.Logo
	}
	return 0
}

func (m *CMsgDOTAGuildCreateRequest) GetBaseLogo() uint64 {
	if m != nil && m.BaseLogo != nil {
		return *m.BaseLogo
	}
	return 0
}

func (m *CMsgDOTAGuildCreateRequest) GetBannerLogo() uint64 {
	if m != nil && m.BannerLogo != nil {
		return *m.BannerLogo
	}
	return 0
}

type CMsgDOTAGuildCreateResponse struct {
	GuildId          *uint32                              `protobuf:"varint,1,opt,name=guild_id" json:"guild_id,omitempty"`
	Errors           []CMsgDOTAGuildCreateResponse_EError `protobuf:"varint,2,rep,name=errors,enum=dota.CMsgDOTAGuildCreateResponse_EError" json:"errors,omitempty"`
	XXX_unrecognized []byte                               `json:"-"`
}

func (m *CMsgDOTAGuildCreateResponse) Reset()                    { *m = CMsgDOTAGuildCreateResponse{} }
func (m *CMsgDOTAGuildCreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CMsgDOTAGuildCreateResponse) ProtoMessage()               {}
func (*CMsgDOTAGuildCreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{4} }

func (m *CMsgDOTAGuildCreateResponse) GetGuildId() uint32 {
	if m != nil && m.GuildId != nil {
		return *m.GuildId
	}
	return 0
}

func (m *CMsgDOTAGuildCreateResponse) GetErrors() []CMsgDOTAGuildCreateResponse_EError {
	if m != nil {
		return m.Errors
	}
	return nil
}

type CMsgDOTAGuildSetAccountRoleRequest struct {
	GuildId          *uint32 `protobuf:"varint,1,opt,name=guild_id" json:"guild_id,omitempty"`
	TargetAccountId  *uint32 `protobuf:"varint,2,opt,name=target_account_id" json:"target_account_id,omitempty"`
	TargetRole       *uint32 `protobuf:"varint,3,opt,name=target_role" json:"target_role,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgDOTAGuildSetAccountRoleRequest) Reset()         { *m = CMsgDOTAGuildSetAccountRoleRequest{} }
func (m *CMsgDOTAGuildSetAccountRoleRequest) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAGuildSetAccountRoleRequest) ProtoMessage()    {}
func (*CMsgDOTAGuildSetAccountRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{5}
}

func (m *CMsgDOTAGuildSetAccountRoleRequest) GetGuildId() uint32 {
	if m != nil && m.GuildId != nil {
		return *m.GuildId
	}
	return 0
}

func (m *CMsgDOTAGuildSetAccountRoleRequest) GetTargetAccountId() uint32 {
	if m != nil && m.TargetAccountId != nil {
		return *m.TargetAccountId
	}
	return 0
}

func (m *CMsgDOTAGuildSetAccountRoleRequest) GetTargetRole() uint32 {
	if m != nil && m.TargetRole != nil {
		return *m.TargetRole
	}
	return 0
}

type CMsgDOTAGuildSetAccountRoleResponse struct {
	Result           *CMsgDOTAGuildSetAccountRoleResponse_EResult `protobuf:"varint,1,opt,name=result,enum=dota.CMsgDOTAGuildSetAccountRoleResponse_EResult,def=0" json:"result,omitempty"`
	XXX_unrecognized []byte                                       `json:"-"`
}

func (m *CMsgDOTAGuildSetAccountRoleResponse) Reset()         { *m = CMsgDOTAGuildSetAccountRoleResponse{} }
func (m *CMsgDOTAGuildSetAccountRoleResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAGuildSetAccountRoleResponse) ProtoMessage()    {}
func (*CMsgDOTAGuildSetAccountRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{6}
}

const Default_CMsgDOTAGuildSetAccountRoleResponse_Result CMsgDOTAGuildSetAccountRoleResponse_EResult = CMsgDOTAGuildSetAccountRoleResponse_SUCCESS

func (m *CMsgDOTAGuildSetAccountRoleResponse) GetResult() CMsgDOTAGuildSetAccountRoleResponse_EResult {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return Default_CMsgDOTAGuildSetAccountRoleResponse_Result
}

type CMsgDOTAGuildInviteAccountRequest struct {
	GuildId          *uint32 `protobuf:"varint,1,opt,name=guild_id" json:"guild_id,omitempty"`
	TargetAccountId  *uint32 `protobuf:"varint,2,opt,name=target_account_id" json:"target_account_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgDOTAGuildInviteAccountRequest) Reset()         { *m = CMsgDOTAGuildInviteAccountRequest{} }
func (m *CMsgDOTAGuildInviteAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAGuildInviteAccountRequest) ProtoMessage()    {}
func (*CMsgDOTAGuildInviteAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{7}
}

func (m *CMsgDOTAGuildInviteAccountRequest) GetGuildId() uint32 {
	if m != nil && m.GuildId != nil {
		return *m.GuildId
	}
	return 0
}

func (m *CMsgDOTAGuildInviteAccountRequest) GetTargetAccountId() uint32 {
	if m != nil && m.TargetAccountId != nil {
		return *m.TargetAccountId
	}
	return 0
}

type CMsgDOTAGuildInviteAccountResponse struct {
	Result           *CMsgDOTAGuildInviteAccountResponse_EResult `protobuf:"varint,1,opt,name=result,enum=dota.CMsgDOTAGuildInviteAccountResponse_EResult,def=0" json:"result,omitempty"`
	XXX_unrecognized []byte                                      `json:"-"`
}

func (m *CMsgDOTAGuildInviteAccountResponse) Reset()         { *m = CMsgDOTAGuildInviteAccountResponse{} }
func (m *CMsgDOTAGuildInviteAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAGuildInviteAccountResponse) ProtoMessage()    {}
func (*CMsgDOTAGuildInviteAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{8}
}

const Default_CMsgDOTAGuildInviteAccountResponse_Result CMsgDOTAGuildInviteAccountResponse_EResult = CMsgDOTAGuildInviteAccountResponse_SUCCESS

func (m *CMsgDOTAGuildInviteAccountResponse) GetResult() CMsgDOTAGuildInviteAccountResponse_EResult {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return Default_CMsgDOTAGuildInviteAccountResponse_Result
}

type CMsgDOTAGuildCancelInviteRequest struct {
	GuildId          *uint32 `protobuf:"varint,1,opt,name=guild_id" json:"guild_id,omitempty"`
	TargetAccountId  *uint32 `protobuf:"varint,2,opt,name=target_account_id" json:"target_account_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgDOTAGuildCancelInviteRequest) Reset()         { *m = CMsgDOTAGuildCancelInviteRequest{} }
func (m *CMsgDOTAGuildCancelInviteRequest) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAGuildCancelInviteRequest) ProtoMessage()    {}
func (*CMsgDOTAGuildCancelInviteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{9}
}

func (m *CMsgDOTAGuildCancelInviteRequest) GetGuildId() uint32 {
	if m != nil && m.GuildId != nil {
		return *m.GuildId
	}
	return 0
}

func (m *CMsgDOTAGuildCancelInviteRequest) GetTargetAccountId() uint32 {
	if m != nil && m.TargetAccountId != nil {
		return *m.TargetAccountId
	}
	return 0
}

type CMsgDOTAGuildCancelInviteResponse struct {
	Result           *CMsgDOTAGuildCancelInviteResponse_EResult `protobuf:"varint,1,opt,name=result,enum=dota.CMsgDOTAGuildCancelInviteResponse_EResult,def=0" json:"result,omitempty"`
	XXX_unrecognized []byte                                     `json:"-"`
}

func (m *CMsgDOTAGuildCancelInviteResponse) Reset()         { *m = CMsgDOTAGuildCancelInviteResponse{} }
func (m *CMsgDOTAGuildCancelInviteResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAGuildCancelInviteResponse) ProtoMessage()    {}
func (*CMsgDOTAGuildCancelInviteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{10}
}

const Default_CMsgDOTAGuildCancelInviteResponse_Result CMsgDOTAGuildCancelInviteResponse_EResult = CMsgDOTAGuildCancelInviteResponse_SUCCESS

func (m *CMsgDOTAGuildCancelInviteResponse) GetResult() CMsgDOTAGuildCancelInviteResponse_EResult {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return Default_CMsgDOTAGuildCancelInviteResponse_Result
}

type CMsgDOTAGuildUpdateDetailsRequest struct {
	GuildId          *uint32 `protobuf:"varint,1,opt,name=guild_id" json:"guild_id,omitempty"`
	Logo             *uint64 `protobuf:"varint,2,opt,name=logo" json:"logo,omitempty"`
	BaseLogo         *uint64 `protobuf:"varint,3,opt,name=base_logo" json:"base_logo,omitempty"`
	BannerLogo       *uint64 `protobuf:"varint,4,opt,name=banner_logo" json:"banner_logo,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgDOTAGuildUpdateDetailsRequest) Reset()         { *m = CMsgDOTAGuildUpdateDetailsRequest{} }
func (m *CMsgDOTAGuildUpdateDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAGuildUpdateDetailsRequest) ProtoMessage()    {}
func (*CMsgDOTAGuildUpdateDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{11}
}

func (m *CMsgDOTAGuildUpdateDetailsRequest) GetGuildId() uint32 {
	if m != nil && m.GuildId != nil {
		return *m.GuildId
	}
	return 0
}

func (m *CMsgDOTAGuildUpdateDetailsRequest) GetLogo() uint64 {
	if m != nil && m.Logo != nil {
		return *m.Logo
	}
	return 0
}

func (m *CMsgDOTAGuildUpdateDetailsRequest) GetBaseLogo() uint64 {
	if m != nil && m.BaseLogo != nil {
		return *m.BaseLogo
	}
	return 0
}

func (m *CMsgDOTAGuildUpdateDetailsRequest) GetBannerLogo() uint64 {
	if m != nil && m.BannerLogo != nil {
		return *m.BannerLogo
	}
	return 0
}

type CMsgDOTAGuildUpdateDetailsResponse struct {
	Result           *CMsgDOTAGuildUpdateDetailsResponse_EResult `protobuf:"varint,1,opt,name=result,enum=dota.CMsgDOTAGuildUpdateDetailsResponse_EResult,def=0" json:"result,omitempty"`
	XXX_unrecognized []byte                                      `json:"-"`
}

func (m *CMsgDOTAGuildUpdateDetailsResponse) Reset()         { *m = CMsgDOTAGuildUpdateDetailsResponse{} }
func (m *CMsgDOTAGuildUpdateDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAGuildUpdateDetailsResponse) ProtoMessage()    {}
func (*CMsgDOTAGuildUpdateDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{12}
}

const Default_CMsgDOTAGuildUpdateDetailsResponse_Result CMsgDOTAGuildUpdateDetailsResponse_EResult = CMsgDOTAGuildUpdateDetailsResponse_SUCCESS

func (m *CMsgDOTAGuildUpdateDetailsResponse) GetResult() CMsgDOTAGuildUpdateDetailsResponse_EResult {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return Default_CMsgDOTAGuildUpdateDetailsResponse_Result
}

type CMsgDOTAGCToGCUpdateOpenGuildPartyRequest struct {
	PartyId          *uint64  `protobuf:"varint,1,opt,name=party_id" json:"party_id,omitempty"`
	GuildId          *uint32  `protobuf:"varint,2,opt,name=guild_id" json:"guild_id,omitempty"`
	MemberAccountIds []uint32 `protobuf:"varint,3,rep,name=member_account_ids" json:"member_account_ids,omitempty"`
	Description      *string  `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CMsgDOTAGCToGCUpdateOpenGuildPartyRequest) Reset() {
	*m = CMsgDOTAGCToGCUpdateOpenGuildPartyRequest{}
}
func (m *CMsgDOTAGCToGCUpdateOpenGuildPartyRequest) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAGCToGCUpdateOpenGuildPartyRequest) ProtoMessage()    {}
func (*CMsgDOTAGCToGCUpdateOpenGuildPartyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{13}
}

func (m *CMsgDOTAGCToGCUpdateOpenGuildPartyRequest) GetPartyId() uint64 {
	if m != nil && m.PartyId != nil {
		return *m.PartyId
	}
	return 0
}

func (m *CMsgDOTAGCToGCUpdateOpenGuildPartyRequest) GetGuildId() uint32 {
	if m != nil && m.GuildId != nil {
		return *m.GuildId
	}
	return 0
}

func (m *CMsgDOTAGCToGCUpdateOpenGuildPartyRequest) GetMemberAccountIds() []uint32 {
	if m != nil {
		return m.MemberAccountIds
	}
	return nil
}

func (m *CMsgDOTAGCToGCUpdateOpenGuildPartyRequest) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

type CMsgDOTAGCToGCUpdateOpenGuildPartyResponse struct {
	MaintainAssociation *bool  `protobuf:"varint,1,opt,name=maintain_association" json:"maintain_association,omitempty"`
	XXX_unrecognized    []byte `json:"-"`
}

func (m *CMsgDOTAGCToGCUpdateOpenGuildPartyResponse) Reset() {
	*m = CMsgDOTAGCToGCUpdateOpenGuildPartyResponse{}
}
func (m *CMsgDOTAGCToGCUpdateOpenGuildPartyResponse) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgDOTAGCToGCUpdateOpenGuildPartyResponse) ProtoMessage() {}
func (*CMsgDOTAGCToGCUpdateOpenGuildPartyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{14}
}

func (m *CMsgDOTAGCToGCUpdateOpenGuildPartyResponse) GetMaintainAssociation() bool {
	if m != nil && m.MaintainAssociation != nil {
		return *m.MaintainAssociation
	}
	return false
}

type CMsgDOTAGCToGCDestroyOpenGuildPartyRequest struct {
	PartyId          *uint64 `protobuf:"varint,1,opt,name=party_id" json:"party_id,omitempty"`
	GuildId          *uint32 `protobuf:"varint,2,opt,name=guild_id" json:"guild_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgDOTAGCToGCDestroyOpenGuildPartyRequest) Reset() {
	*m = CMsgDOTAGCToGCDestroyOpenGuildPartyRequest{}
}
func (m *CMsgDOTAGCToGCDestroyOpenGuildPartyRequest) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgDOTAGCToGCDestroyOpenGuildPartyRequest) ProtoMessage() {}
func (*CMsgDOTAGCToGCDestroyOpenGuildPartyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{15}
}

func (m *CMsgDOTAGCToGCDestroyOpenGuildPartyRequest) GetPartyId() uint64 {
	if m != nil && m.PartyId != nil {
		return *m.PartyId
	}
	return 0
}

func (m *CMsgDOTAGCToGCDestroyOpenGuildPartyRequest) GetGuildId() uint32 {
	if m != nil && m.GuildId != nil {
		return *m.GuildId
	}
	return 0
}

type CMsgDOTAGCToGCDestroyOpenGuildPartyResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CMsgDOTAGCToGCDestroyOpenGuildPartyResponse) Reset() {
	*m = CMsgDOTAGCToGCDestroyOpenGuildPartyResponse{}
}
func (m *CMsgDOTAGCToGCDestroyOpenGuildPartyResponse) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgDOTAGCToGCDestroyOpenGuildPartyResponse) ProtoMessage() {}
func (*CMsgDOTAGCToGCDestroyOpenGuildPartyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{16}
}

type CMsgDOTAPartySetOpenGuildRequest struct {
	GuildId          *uint32 `protobuf:"varint,1,opt,name=guild_id" json:"guild_id,omitempty"`
	Description      *string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgDOTAPartySetOpenGuildRequest) Reset()         { *m = CMsgDOTAPartySetOpenGuildRequest{} }
func (m *CMsgDOTAPartySetOpenGuildRequest) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAPartySetOpenGuildRequest) ProtoMessage()    {}
func (*CMsgDOTAPartySetOpenGuildRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{17}
}

func (m *CMsgDOTAPartySetOpenGuildRequest) GetGuildId() uint32 {
	if m != nil && m.GuildId != nil {
		return *m.GuildId
	}
	return 0
}

func (m *CMsgDOTAPartySetOpenGuildRequest) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

type CMsgDOTAPartySetOpenGuildResponse struct {
	Result           *CMsgDOTAPartySetOpenGuildResponse_EResult `protobuf:"varint,1,opt,name=result,enum=dota.CMsgDOTAPartySetOpenGuildResponse_EResult,def=0" json:"result,omitempty"`
	XXX_unrecognized []byte                                     `json:"-"`
}

func (m *CMsgDOTAPartySetOpenGuildResponse) Reset()         { *m = CMsgDOTAPartySetOpenGuildResponse{} }
func (m *CMsgDOTAPartySetOpenGuildResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAPartySetOpenGuildResponse) ProtoMessage()    {}
func (*CMsgDOTAPartySetOpenGuildResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{18}
}

const Default_CMsgDOTAPartySetOpenGuildResponse_Result CMsgDOTAPartySetOpenGuildResponse_EResult = CMsgDOTAPartySetOpenGuildResponse_SUCCESS

func (m *CMsgDOTAPartySetOpenGuildResponse) GetResult() CMsgDOTAPartySetOpenGuildResponse_EResult {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return Default_CMsgDOTAPartySetOpenGuildResponse_Result
}

type CMsgDOTAJoinOpenGuildPartyRequest struct {
	PartyId          *uint64 `protobuf:"varint,1,opt,name=party_id" json:"party_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgDOTAJoinOpenGuildPartyRequest) Reset()         { *m = CMsgDOTAJoinOpenGuildPartyRequest{} }
func (m *CMsgDOTAJoinOpenGuildPartyRequest) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAJoinOpenGuildPartyRequest) ProtoMessage()    {}
func (*CMsgDOTAJoinOpenGuildPartyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{19}
}

func (m *CMsgDOTAJoinOpenGuildPartyRequest) GetPartyId() uint64 {
	if m != nil && m.PartyId != nil {
		return *m.PartyId
	}
	return 0
}

type CMsgDOTAJoinOpenGuildPartyResponse struct {
	Result           *CMsgDOTAJoinOpenGuildPartyResponse_EResult `protobuf:"varint,1,opt,name=result,enum=dota.CMsgDOTAJoinOpenGuildPartyResponse_EResult,def=0" json:"result,omitempty"`
	XXX_unrecognized []byte                                      `json:"-"`
}

func (m *CMsgDOTAJoinOpenGuildPartyResponse) Reset()         { *m = CMsgDOTAJoinOpenGuildPartyResponse{} }
func (m *CMsgDOTAJoinOpenGuildPartyResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAJoinOpenGuildPartyResponse) ProtoMessage()    {}
func (*CMsgDOTAJoinOpenGuildPartyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{20}
}

const Default_CMsgDOTAJoinOpenGuildPartyResponse_Result CMsgDOTAJoinOpenGuildPartyResponse_EResult = CMsgDOTAJoinOpenGuildPartyResponse_SUCCESS

func (m *CMsgDOTAJoinOpenGuildPartyResponse) GetResult() CMsgDOTAJoinOpenGuildPartyResponse_EResult {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return Default_CMsgDOTAJoinOpenGuildPartyResponse_Result
}

type CMsgDOTAGuildOpenPartyRefresh struct {
	GuildId          *uint32                                    `protobuf:"varint,1,opt,name=guild_id" json:"guild_id,omitempty"`
	OpenParties      []*CMsgDOTAGuildOpenPartyRefresh_OpenParty `protobuf:"bytes,2,rep,name=open_parties" json:"open_parties,omitempty"`
	XXX_unrecognized []byte                                     `json:"-"`
}

func (m *CMsgDOTAGuildOpenPartyRefresh) Reset()                    { *m = CMsgDOTAGuildOpenPartyRefresh{} }
func (m *CMsgDOTAGuildOpenPartyRefresh) String() string            { return proto.CompactTextString(m) }
func (*CMsgDOTAGuildOpenPartyRefresh) ProtoMessage()               {}
func (*CMsgDOTAGuildOpenPartyRefresh) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{21} }

func (m *CMsgDOTAGuildOpenPartyRefresh) GetGuildId() uint32 {
	if m != nil && m.GuildId != nil {
		return *m.GuildId
	}
	return 0
}

func (m *CMsgDOTAGuildOpenPartyRefresh) GetOpenParties() []*CMsgDOTAGuildOpenPartyRefresh_OpenParty {
	if m != nil {
		return m.OpenParties
	}
	return nil
}

type CMsgDOTAGuildOpenPartyRefresh_OpenParty struct {
	PartyId          *uint64  `protobuf:"varint,1,opt,name=party_id" json:"party_id,omitempty"`
	MemberAccountIds []uint32 `protobuf:"varint,2,rep,name=member_account_ids" json:"member_account_ids,omitempty"`
	TimeCreated      *uint32  `protobuf:"varint,3,opt,name=time_created" json:"time_created,omitempty"`
	Description      *string  `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CMsgDOTAGuildOpenPartyRefresh_OpenParty) Reset() {
	*m = CMsgDOTAGuildOpenPartyRefresh_OpenParty{}
}
func (m *CMsgDOTAGuildOpenPartyRefresh_OpenParty) String() string { return proto.CompactTextString(m) }
func (*CMsgDOTAGuildOpenPartyRefresh_OpenParty) ProtoMessage()    {}
func (*CMsgDOTAGuildOpenPartyRefresh_OpenParty) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{21, 0}
}

func (m *CMsgDOTAGuildOpenPartyRefresh_OpenParty) GetPartyId() uint64 {
	if m != nil && m.PartyId != nil {
		return *m.PartyId
	}
	return 0
}

func (m *CMsgDOTAGuildOpenPartyRefresh_OpenParty) GetMemberAccountIds() []uint32 {
	if m != nil {
		return m.MemberAccountIds
	}
	return nil
}

func (m *CMsgDOTAGuildOpenPartyRefresh_OpenParty) GetTimeCreated() uint32 {
	if m != nil && m.TimeCreated != nil {
		return *m.TimeCreated
	}
	return 0
}

func (m *CMsgDOTAGuildOpenPartyRefresh_OpenParty) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

type CMsgDOTARequestGuildData struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CMsgDOTARequestGuildData) Reset()                    { *m = CMsgDOTARequestGuildData{} }
func (m *CMsgDOTARequestGuildData) String() string            { return proto.CompactTextString(m) }
func (*CMsgDOTARequestGuildData) ProtoMessage()               {}
func (*CMsgDOTARequestGuildData) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{22} }

type CMsgDOTAGuildInviteData struct {
	InvitedToGuild   *bool   `protobuf:"varint,1,opt,name=invited_to_guild" json:"invited_to_guild,omitempty"`
	GuildId          *uint32 `protobuf:"varint,2,opt,name=guild_id" json:"guild_id,omitempty"`
	GuildName        *string `protobuf:"bytes,3,opt,name=guild_name" json:"guild_name,omitempty"`
	GuildTag         *string `protobuf:"bytes,4,opt,name=guild_tag" json:"guild_tag,omitempty"`
	Logo             *uint64 `protobuf:"varint,5,opt,name=logo" json:"logo,omitempty"`
	Inviter          *uint32 `protobuf:"varint,6,opt,name=inviter" json:"inviter,omitempty"`
	InviterName      *string `protobuf:"bytes,7,opt,name=inviter_name" json:"inviter_name,omitempty"`
	MemberCount      *uint32 `protobuf:"varint,8,opt,name=member_count" json:"member_count,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgDOTAGuildInviteData) Reset()                    { *m = CMsgDOTAGuildInviteData{} }
func (m *CMsgDOTAGuildInviteData) String() string            { return proto.CompactTextString(m) }
func (*CMsgDOTAGuildInviteData) ProtoMessage()               {}
func (*CMsgDOTAGuildInviteData) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{23} }

func (m *CMsgDOTAGuildInviteData) GetInvitedToGuild() bool {
	if m != nil && m.InvitedToGuild != nil {
		return *m.InvitedToGuild
	}
	return false
}

func (m *CMsgDOTAGuildInviteData) GetGuildId() uint32 {
	if m != nil && m.GuildId != nil {
		return *m.GuildId
	}
	return 0
}

func (m *CMsgDOTAGuildInviteData) GetGuildName() string {
	if m != nil && m.GuildName != nil {
		return *m.GuildName
	}
	return ""
}

func (m *CMsgDOTAGuildInviteData) GetGuildTag() string {
	if m != nil && m.GuildTag != nil {
		return *m.GuildTag
	}
	return ""
}

func (m *CMsgDOTAGuildInviteData) GetLogo() uint64 {
	if m != nil && m.Logo != nil {
		return *m.Logo
	}
	return 0
}

func (m *CMsgDOTAGuildInviteData) GetInviter() uint32 {
	if m != nil && m.Inviter != nil {
		return *m.Inviter
	}
	return 0
}

func (m *CMsgDOTAGuildInviteData) GetInviterName() string {
	if m != nil && m.InviterName != nil {
		return *m.InviterName
	}
	return ""
}

func (m *CMsgDOTAGuildInviteData) GetMemberCount() uint32 {
	if m != nil && m.MemberCount != nil {
		return *m.MemberCount
	}
	return 0
}

type CMsgDOTAGuildUpdateMessage struct {
	Message          *string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	GuildId          *uint32 `protobuf:"varint,2,opt,name=guild_id" json:"guild_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgDOTAGuildUpdateMessage) Reset()                    { *m = CMsgDOTAGuildUpdateMessage{} }
func (m *CMsgDOTAGuildUpdateMessage) String() string            { return proto.CompactTextString(m) }
func (*CMsgDOTAGuildUpdateMessage) ProtoMessage()               {}
func (*CMsgDOTAGuildUpdateMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{24} }

func (m *CMsgDOTAGuildUpdateMessage) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *CMsgDOTAGuildUpdateMessage) GetGuildId() uint32 {
	if m != nil && m.GuildId != nil {
		return *m.GuildId
	}
	return 0
}

type CMsgDOTAGuildEditLogoRequest struct {
	GuildId          *uint32 `protobuf:"varint,1,opt,name=guild_id" json:"guild_id,omitempty"`
	Logo             *uint64 `protobuf:"varint,2,opt,name=logo" json:"logo,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgDOTAGuildEditLogoRequest) Reset()                    { *m = CMsgDOTAGuildEditLogoRequest{} }
func (m *CMsgDOTAGuildEditLogoRequest) String() string            { return proto.CompactTextString(m) }
func (*CMsgDOTAGuildEditLogoRequest) ProtoMessage()               {}
func (*CMsgDOTAGuildEditLogoRequest) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{25} }

func (m *CMsgDOTAGuildEditLogoRequest) GetGuildId() uint32 {
	if m != nil && m.GuildId != nil {
		return *m.GuildId
	}
	return 0
}

func (m *CMsgDOTAGuildEditLogoRequest) GetLogo() uint64 {
	if m != nil && m.Logo != nil {
		return *m.Logo
	}
	return 0
}

type CMsgDOTAGuildEditLogoResponse struct {
	GuildId          *uint32                                `protobuf:"varint,1,opt,name=guild_id" json:"guild_id,omitempty"`
	Result           *CMsgDOTAGuildEditLogoResponse_EResult `protobuf:"varint,2,opt,name=result,enum=dota.CMsgDOTAGuildEditLogoResponse_EResult,def=0" json:"result,omitempty"`
	XXX_unrecognized []byte                                 `json:"-"`
}

func (m *CMsgDOTAGuildEditLogoResponse) Reset()                    { *m = CMsgDOTAGuildEditLogoResponse{} }
func (m *CMsgDOTAGuildEditLogoResponse) String() string            { return proto.CompactTextString(m) }
func (*CMsgDOTAGuildEditLogoResponse) ProtoMessage()               {}
func (*CMsgDOTAGuildEditLogoResponse) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{26} }

const Default_CMsgDOTAGuildEditLogoResponse_Result CMsgDOTAGuildEditLogoResponse_EResult = CMsgDOTAGuildEditLogoResponse_SUCCESS

func (m *CMsgDOTAGuildEditLogoResponse) GetGuildId() uint32 {
	if m != nil && m.GuildId != nil {
		return *m.GuildId
	}
	return 0
}

func (m *CMsgDOTAGuildEditLogoResponse) GetResult() CMsgDOTAGuildEditLogoResponse_EResult {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return Default_CMsgDOTAGuildEditLogoResponse_Result
}

func init() {
	proto.RegisterType((*CMsgDOTAGuildSDO)(nil), "dota.CMsgDOTAGuildSDO")
	proto.RegisterType((*CMsgDOTAGuildSDO_Member)(nil), "dota.CMsgDOTAGuildSDO.Member")
	proto.RegisterType((*CMsgDOTAGuildSDO_Invitation)(nil), "dota.CMsgDOTAGuildSDO.Invitation")
	proto.RegisterType((*CMsgDOTAGuildAuditSDO)(nil), "dota.CMsgDOTAGuildAuditSDO")
	proto.RegisterType((*CMsgDOTAGuildAuditSDO_Entry)(nil), "dota.CMsgDOTAGuildAuditSDO.Entry")
	proto.RegisterType((*CMsgDOTAAccountGuildMembershipsSDO)(nil), "dota.CMsgDOTAAccountGuildMembershipsSDO")
	proto.RegisterType((*CMsgDOTAAccountGuildMembershipsSDO_Membership)(nil), "dota.CMsgDOTAAccountGuildMembershipsSDO.Membership")
	proto.RegisterType((*CMsgDOTAAccountGuildMembershipsSDO_Invitation)(nil), "dota.CMsgDOTAAccountGuildMembershipsSDO.Invitation")
	proto.RegisterType((*CMsgDOTAGuildCreateRequest)(nil), "dota.CMsgDOTAGuildCreateRequest")
	proto.RegisterType((*CMsgDOTAGuildCreateResponse)(nil), "dota.CMsgDOTAGuildCreateResponse")
	proto.RegisterType((*CMsgDOTAGuildSetAccountRoleRequest)(nil), "dota.CMsgDOTAGuildSetAccountRoleRequest")
	proto.RegisterType((*CMsgDOTAGuildSetAccountRoleResponse)(nil), "dota.CMsgDOTAGuildSetAccountRoleResponse")
	proto.RegisterType((*CMsgDOTAGuildInviteAccountRequest)(nil), "dota.CMsgDOTAGuildInviteAccountRequest")
	proto.RegisterType((*CMsgDOTAGuildInviteAccountResponse)(nil), "dota.CMsgDOTAGuildInviteAccountResponse")
	proto.RegisterType((*CMsgDOTAGuildCancelInviteRequest)(nil), "dota.CMsgDOTAGuildCancelInviteRequest")
	proto.RegisterType((*CMsgDOTAGuildCancelInviteResponse)(nil), "dota.CMsgDOTAGuildCancelInviteResponse")
	proto.RegisterType((*CMsgDOTAGuildUpdateDetailsRequest)(nil), "dota.CMsgDOTAGuildUpdateDetailsRequest")
	proto.RegisterType((*CMsgDOTAGuildUpdateDetailsResponse)(nil), "dota.CMsgDOTAGuildUpdateDetailsResponse")
	proto.RegisterType((*CMsgDOTAGCToGCUpdateOpenGuildPartyRequest)(nil), "dota.CMsgDOTAGCToGCUpdateOpenGuildPartyRequest")
	proto.RegisterType((*CMsgDOTAGCToGCUpdateOpenGuildPartyResponse)(nil), "dota.CMsgDOTAGCToGCUpdateOpenGuildPartyResponse")
	proto.RegisterType((*CMsgDOTAGCToGCDestroyOpenGuildPartyRequest)(nil), "dota.CMsgDOTAGCToGCDestroyOpenGuildPartyRequest")
	proto.RegisterType((*CMsgDOTAGCToGCDestroyOpenGuildPartyResponse)(nil), "dota.CMsgDOTAGCToGCDestroyOpenGuildPartyResponse")
	proto.RegisterType((*CMsgDOTAPartySetOpenGuildRequest)(nil), "dota.CMsgDOTAPartySetOpenGuildRequest")
	proto.RegisterType((*CMsgDOTAPartySetOpenGuildResponse)(nil), "dota.CMsgDOTAPartySetOpenGuildResponse")
	proto.RegisterType((*CMsgDOTAJoinOpenGuildPartyRequest)(nil), "dota.CMsgDOTAJoinOpenGuildPartyRequest")
	proto.RegisterType((*CMsgDOTAJoinOpenGuildPartyResponse)(nil), "dota.CMsgDOTAJoinOpenGuildPartyResponse")
	proto.RegisterType((*CMsgDOTAGuildOpenPartyRefresh)(nil), "dota.CMsgDOTAGuildOpenPartyRefresh")
	proto.RegisterType((*CMsgDOTAGuildOpenPartyRefresh_OpenParty)(nil), "dota.CMsgDOTAGuildOpenPartyRefresh.OpenParty")
	proto.RegisterType((*CMsgDOTARequestGuildData)(nil), "dota.CMsgDOTARequestGuildData")
	proto.RegisterType((*CMsgDOTAGuildInviteData)(nil), "dota.CMsgDOTAGuildInviteData")
	proto.RegisterType((*CMsgDOTAGuildUpdateMessage)(nil), "dota.CMsgDOTAGuildUpdateMessage")
	proto.RegisterType((*CMsgDOTAGuildEditLogoRequest)(nil), "dota.CMsgDOTAGuildEditLogoRequest")
	proto.RegisterType((*CMsgDOTAGuildEditLogoResponse)(nil), "dota.CMsgDOTAGuildEditLogoResponse")
	proto.RegisterEnum("dota.CMsgDOTAGuildCreateResponse_EError", CMsgDOTAGuildCreateResponse_EError_name, CMsgDOTAGuildCreateResponse_EError_value)
	proto.RegisterEnum("dota.CMsgDOTAGuildSetAccountRoleResponse_EResult", CMsgDOTAGuildSetAccountRoleResponse_EResult_name, CMsgDOTAGuildSetAccountRoleResponse_EResult_value)
	proto.RegisterEnum("dota.CMsgDOTAGuildInviteAccountResponse_EResult", CMsgDOTAGuildInviteAccountResponse_EResult_name, CMsgDOTAGuildInviteAccountResponse_EResult_value)
	proto.RegisterEnum("dota.CMsgDOTAGuildCancelInviteResponse_EResult", CMsgDOTAGuildCancelInviteResponse_EResult_name, CMsgDOTAGuildCancelInviteResponse_EResult_value)
	proto.RegisterEnum("dota.CMsgDOTAGuildUpdateDetailsResponse_EResult", CMsgDOTAGuildUpdateDetailsResponse_EResult_name, CMsgDOTAGuildUpdateDetailsResponse_EResult_value)
	proto.RegisterEnum("dota.CMsgDOTAPartySetOpenGuildResponse_EResult", CMsgDOTAPartySetOpenGuildResponse_EResult_name, CMsgDOTAPartySetOpenGuildResponse_EResult_value)
	proto.RegisterEnum("dota.CMsgDOTAJoinOpenGuildPartyResponse_EResult", CMsgDOTAJoinOpenGuildPartyResponse_EResult_name, CMsgDOTAJoinOpenGuildPartyResponse_EResult_value)
	proto.RegisterEnum("dota.CMsgDOTAGuildEditLogoResponse_EResult", CMsgDOTAGuildEditLogoResponse_EResult_name, CMsgDOTAGuildEditLogoResponse_EResult_value)
}

var fileDescriptor12 = []byte{
	// 1426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x57, 0x41, 0x8f, 0xdb, 0x54,
	0x10, 0xae, 0x9d, 0x6c, 0xb2, 0x99, 0xec, 0x2e, 0xa9, 0xdb, 0xd2, 0x34, 0x6d, 0xd1, 0xf6, 0x71,
	0x29, 0x94, 0x06, 0x58, 0x04, 0x42, 0x1c, 0xa8, 0xdc, 0xc4, 0xdd, 0x4d, 0x49, 0xe2, 0x55, 0x92,
	0x45, 0xf4, 0x64, 0x79, 0x93, 0xd7, 0xd4, 0x90, 0xc4, 0xc1, 0xf6, 0x56, 0xf4, 0xd6, 0x1f, 0xc0,
	0x2f, 0x40, 0x88, 0x23, 0x27, 0xae, 0x88, 0x23, 0x12, 0x27, 0xae, 0x88, 0x2b, 0x3f, 0x80, 0x5f,
	0xc0, 0x99, 0x79, 0xef, 0xd9, 0x8e, 0xed, 0x3c, 0x43, 0xb6, 0x94, 0x5b, 0x3c, 0xef, 0xcd, 0xbc,
	0x99, 0x6f, 0xbe, 0x99, 0xcc, 0x00, 0x99, 0xb8, 0x81, 0x6d, 0x4d, 0xc7, 0x73, 0xea, 0xfb, 0xf6,
	0x94, 0xfa, 0xd6, 0x78, 0xe6, 0xd0, 0x45, 0x60, 0x4d, 0xcf, 0x9c, 0xd9, 0xa4, 0xb9, 0xf4, 0xdc,
	0xc0, 0xd5, 0x8a, 0xec, 0x0e, 0xf9, 0xa5, 0x00, 0xb5, 0x56, 0xcf, 0x9f, 0xb6, 0xcd, 0x91, 0x7e,
	0xc8, 0x4e, 0x87, 0x6d, 0x53, 0xab, 0xc1, 0x36, 0xbf, 0x69, 0x39, 0x93, 0xba, 0xb2, 0xaf, 0xdc,
	0xde, 0xd5, 0x76, 0xa0, 0xb8, 0xb0, 0xe7, 0xb4, 0xae, 0xe2, 0x57, 0x45, 0xab, 0x42, 0x21, 0xb0,
	0xa7, 0xf5, 0x02, 0xff, 0xb8, 0x0c, 0x3b, 0x81, 0x33, 0xa7, 0xd6, 0xd8, 0xa3, 0x76, 0x40, 0x27,
	0xf5, 0x22, 0x57, 0x78, 0x15, 0xf6, 0xb8, 0x74, 0xe2, 0xf8, 0xa7, 0xf6, 0x62, 0x82, 0xf2, 0xad,
	0xc8, 0xd0, 0xcc, 0x9d, 0xba, 0xf5, 0x12, 0x7e, 0x15, 0xb5, 0x8b, 0x50, 0x39, 0xb5, 0x7d, 0x6a,
	0x71, 0x51, 0x99, 0x8b, 0x2e, 0x41, 0x15, 0x15, 0x16, 0xd4, 0x13, 0xc2, 0x6d, 0x2e, 0x6c, 0x42,
	0x79, 0x4e, 0xe7, 0xa7, 0xd4, 0xf3, 0xeb, 0x95, 0xfd, 0xc2, 0xed, 0xea, 0xc1, 0xcd, 0x26, 0xf3,
	0xbe, 0x99, 0xf5, 0xbc, 0xd9, 0xe3, 0xb7, 0xb4, 0x0f, 0xa0, 0xea, 0x2c, 0x9e, 0x3a, 0x81, 0x1d,
	0x38, 0xee, 0xc2, 0xaf, 0x03, 0xd7, 0xb9, 0x95, 0xa3, 0xd3, 0x89, 0x6f, 0x6a, 0xaf, 0xb0, 0x77,
	0x38, 0x64, 0xf5, 0x2a, 0x0f, 0xee, 0x12, 0x33, 0x84, 0x91, 0xcd, 0x11, 0x3d, 0x7b, 0x56, 0xdf,
	0x41, 0xe1, 0x76, 0xe3, 0x1e, 0x94, 0xc2, 0x77, 0x34, 0x00, 0x7b, 0x3c, 0x76, 0xcf, 0x10, 0xda,
	0x18, 0x2a, 0x54, 0xe1, 0x91, 0x7f, 0xee, 0x3a, 0x0b, 0x0c, 0x5b, 0x8d, 0xc2, 0xf6, 0xdc, 0x19,
	0xe5, 0x90, 0xed, 0x36, 0xfa, 0x00, 0x89, 0x47, 0x65, 0x46, 0x10, 0x18, 0x6e, 0xc4, 0xc7, 0x77,
	0x43, 0x13, 0xd7, 0xe0, 0xe2, 0xea, 0x1a, 0x3b, 0x98, 0x50, 0x4f, 0xd8, 0x23, 0x5f, 0xab, 0x70,
	0x25, 0x15, 0x96, 0x7e, 0x36, 0x71, 0x02, 0x79, 0x26, 0x0f, 0xa0, 0x8c, 0x36, 0x3d, 0x87, 0xfa,
	0x68, 0x37, 0x0f, 0x96, 0x48, 0xbf, 0x69, 0xe0, 0xd5, 0x67, 0x8d, 0x1f, 0x14, 0xd8, 0xe2, 0xbf,
	0x58, 0x70, 0xf4, 0x29, 0x63, 0x92, 0x83, 0xcf, 0x7f, 0x95, 0x76, 0xd6, 0x0f, 0xec, 0xf9, 0x32,
	0x74, 0x76, 0x0f, 0x4a, 0xf6, 0x98, 0x45, 0x27, 0x3c, 0xd4, 0x6e, 0xc0, 0xe5, 0x84, 0xf3, 0x1e,
	0xfd, 0xf2, 0x0c, 0xaf, 0xbb, 0x5e, 0x48, 0x96, 0x74, 0x68, 0x81, 0xed, 0x4d, 0x69, 0x10, 0xf2,
	0xa5, 0x0e, 0x35, 0x8f, 0x3e, 0xa6, 0x1e, 0x5d, 0x8c, 0x91, 0x4c, 0x36, 0xb2, 0xda, 0xe6, 0xdc,
	0x91, 0x9d, 0x9c, 0x72, 0x0a, 0xed, 0x92, 0x5f, 0x55, 0x20, 0x51, 0x38, 0xba, 0xb0, 0xcb, 0xa3,
	0x12, 0x49, 0xf3, 0x9f, 0x38, 0x4b, 0x9f, 0x61, 0x23, 0xc3, 0xfd, 0x08, 0xaa, 0xf3, 0xd5, 0xad,
	0x10, 0xa1, 0xf7, 0xd2, 0x08, 0xe5, 0x9b, 0x6c, 0xae, 0x3e, 0x99, 0xa5, 0x24, 0x05, 0x0b, 0xe7,
	0xb4, 0xb4, 0xe2, 0x47, 0xe3, 0x2d, 0x80, 0x84, 0x5d, 0x69, 0x6d, 0x72, 0x6e, 0x71, 0xe4, 0x1b,
	0xdd, 0x14, 0xb7, 0xd6, 0x6f, 0x9f, 0x8f, 0x59, 0x73, 0x68, 0xa4, 0x88, 0xd1, 0xe2, 0x45, 0x3e,
	0x10, 0xf9, 0x8b, 0xbb, 0x82, 0x92, 0xec, 0x0a, 0xa2, 0x45, 0x44, 0x75, 0x5e, 0x58, 0xaf, 0xf3,
	0xa2, 0xac, 0xce, 0x59, 0xb6, 0x8b, 0xe4, 0x67, 0x15, 0xae, 0x4b, 0xdf, 0xf3, 0x97, 0x08, 0x22,
	0x95, 0x84, 0xf3, 0x21, 0x94, 0xa8, 0xe7, 0xb9, 0x9e, 0xc8, 0xd5, 0xde, 0xc1, 0x6d, 0x09, 0x9b,
	0xd3, 0x46, 0x9a, 0x86, 0xc1, 0x14, 0xc8, 0xef, 0x0a, 0x94, 0xc4, 0x4f, 0x2c, 0xfb, 0xea, 0x49,
	0x7f, 0x78, 0x6c, 0xb4, 0x3a, 0x0f, 0x3a, 0x46, 0xbb, 0x76, 0x01, 0xe9, 0x0b, 0x7d, 0xbd, 0x67,
	0x58, 0x46, 0xef, 0x78, 0xf4, 0xa8, 0xa6, 0x68, 0x57, 0xe1, 0x12, 0xff, 0xbe, 0xaf, 0xb7, 0xad,
	0xd6, 0x91, 0x3e, 0xd0, 0x5b, 0x23, 0x63, 0x30, 0xac, 0xa9, 0x18, 0xd8, 0x2e, 0x3f, 0x18, 0x99,
	0xa6, 0xd5, 0x35, 0xfb, 0x87, 0xb5, 0x42, 0xac, 0x3b, 0xd2, 0x3f, 0x31, 0xfa, 0xb5, 0xa2, 0xb6,
	0x0b, 0x15, 0xf4, 0x23, 0x34, 0xb5, 0x85, 0x8d, 0x51, 0x63, 0x9f, 0x19, 0x4b, 0x25, 0x0c, 0x6d,
	0x87, 0xc9, 0x63, 0x43, 0x65, 0xed, 0x3a, 0x5c, 0xd5, 0x5b, 0x2d, 0xf3, 0xa4, 0x3f, 0xe2, 0xd2,
	0x9e, 0xde, 0x7f, 0x64, 0x1d, 0x9e, 0x74, 0xba, 0xed, 0x61, 0x6d, 0x9b, 0x99, 0xe9, 0x9a, 0x87,
	0xa6, 0x75, 0x72, 0xdc, 0x35, 0xd1, 0xd4, 0x03, 0xbd, 0xd3, 0x45, 0xcf, 0x2b, 0xe4, 0xf1, 0x8a,
	0xfa, 0xa2, 0xc1, 0xd1, 0x20, 0x64, 0xd9, 0x00, 0x39, 0x12, 0x25, 0x6e, 0x1d, 0x47, 0xe4, 0x80,
	0xa8, 0x3b, 0x2b, 0x51, 0x13, 0x6a, 0xdc, 0xd0, 0xc4, 0xd1, 0xaa, 0x85, 0x91, 0x6f, 0x54, 0x78,
	0xfd, 0x1f, 0x1f, 0x0a, 0x33, 0xf6, 0x10, 0x4a, 0x1e, 0xf5, 0xcf, 0x66, 0x01, 0x7f, 0x67, 0xef,
	0xe0, 0x5d, 0x59, 0x13, 0x96, 0xaa, 0x36, 0x8d, 0x01, 0x57, 0xfc, 0xa8, 0x3c, 0x3c, 0x69, 0xb5,
	0x8c, 0xe1, 0x90, 0x7c, 0xaf, 0x40, 0x39, 0x14, 0x22, 0xd9, 0x22, 0x31, 0xa6, 0xeb, 0x0a, 0x5c,
	0x34, 0x06, 0x03, 0x73, 0x60, 0x25, 0xb3, 0xc8, 0xb3, 0x26, 0xc4, 0x7d, 0xd3, 0x3a, 0x36, 0x06,
	0xbd, 0xce, 0x70, 0xd8, 0x31, 0xfb, 0x98, 0xb5, 0x6b, 0x70, 0x25, 0x3e, 0x30, 0x47, 0x47, 0xc6,
	0xc0, 0xea, 0x1a, 0x7a, 0xdb, 0x18, 0x60, 0xf6, 0x6e, 0xc1, 0x4d, 0x71, 0x94, 0x07, 0x7d, 0x51,
	0xdb, 0x87, 0x1b, 0xe2, 0x0a, 0x97, 0xac, 0x2e, 0xf4, 0x8c, 0xde, 0x7d, 0x96, 0xcb, 0x2d, 0x72,
	0x0c, 0xb7, 0x52, 0x01, 0xf2, 0x82, 0xa4, 0x51, 0x8c, 0x2f, 0x90, 0x03, 0xf2, 0xa7, 0x9a, 0xc9,
	0x6b, 0xc6, 0x64, 0x88, 0x76, 0x27, 0x83, 0xf6, 0x3b, 0x12, 0xb4, 0xa5, 0x9a, 0xeb, 0x60, 0xff,
	0xf5, 0xb2, 0xc0, 0x5e, 0x43, 0x54, 0xef, 0x0e, 0x10, 0xed, 0x47, 0x56, 0xa7, 0xff, 0x69, 0x67,
	0x84, 0xba, 0x05, 0x8d, 0xc0, 0x6b, 0x79, 0x57, 0x04, 0xc8, 0x88, 0xfa, 0xda, 0x9d, 0x18, 0x77,
	0x61, 0x07, 0x71, 0xcf, 0xcd, 0x4c, 0x74, 0xa3, 0xf4, 0xef, 0xe9, 0x2d, 0x13, 0x13, 0xf6, 0xd3,
	0xdd, 0xc3, 0xc6, 0x3f, 0x98, 0x99, 0x40, 0xed, 0x85, 0x72, 0xf7, 0xa3, 0x92, 0xa1, 0x43, 0xda,
	0x62, 0x98, 0xba, 0xa3, 0x4c, 0xea, 0xde, 0x96, 0x35, 0x32, 0x89, 0xe2, 0x7a, 0xe6, 0x1e, 0xbc,
	0x9c, 0xc4, 0x91, 0x2f, 0x32, 0x6e, 0x9f, 0x2c, 0xf1, 0x5f, 0x96, 0xb6, 0x69, 0x60, 0x3b, 0x33,
	0x3f, 0x1f, 0x89, 0xa8, 0xf3, 0xab, 0xeb, 0x9d, 0xbf, 0x20, 0xeb, 0xfc, 0xfc, 0xef, 0x80, 0xfc,
	0xa4, 0x64, 0x08, 0x9e, 0x79, 0xed, 0x1c, 0x04, 0x97, 0x6a, 0xfe, 0x7f, 0x30, 0x3d, 0x57, 0xe0,
	0x8d, 0xf8, 0xfd, 0xd6, 0xc8, 0x3d, 0x6c, 0x09, 0x07, 0xcc, 0x25, 0x5d, 0x70, 0x7f, 0x8e, 0x6d,
	0x2f, 0x78, 0x96, 0xc0, 0x6b, 0xc9, 0xbe, 0x23, 0xbc, 0x8a, 0x29, 0x04, 0x45, 0xc3, 0x6d, 0x80,
	0x26, 0x86, 0x90, 0x04, 0x97, 0xc4, 0x04, 0xc1, 0x9b, 0xf1, 0x84, 0xfa, 0x63, 0xcf, 0x59, 0xf2,
	0xe9, 0x8a, 0x81, 0x57, 0x21, 0x0f, 0xe1, 0xcd, 0x4d, 0x3c, 0x08, 0x31, 0xc4, 0x59, 0x6c, 0x6e,
	0x3b, 0x38, 0xcf, 0x3a, 0x0b, 0xcb, 0xf6, 0x7d, 0x77, 0xec, 0xf0, 0x59, 0x81, 0xbb, 0xb3, 0x8d,
	0xbd, 0x2b, 0x63, 0xab, 0x8d, 0x6e, 0x7b, 0xee, 0xb3, 0x17, 0x0e, 0x87, 0xdc, 0x85, 0x3b, 0x1b,
	0x59, 0x14, 0xee, 0x91, 0xce, 0xaa, 0xfe, 0xf8, 0x01, 0xfe, 0x3b, 0xc4, 0x37, 0xf3, 0x59, 0x97,
	0xc1, 0x85, 0x0f, 0x21, 0xe4, 0xdb, 0x44, 0xe5, 0x49, 0x6c, 0x6d, 0x56, 0x79, 0xb9, 0x8a, 0xeb,
	0x94, 0xba, 0x7b, 0x2e, 0x4a, 0x91, 0xf7, 0x57, 0xde, 0x3d, 0xc4, 0x65, 0x61, 0x43, 0x84, 0xc9,
	0x77, 0x89, 0x52, 0x91, 0xe9, 0x6d, 0x56, 0x2a, 0xf9, 0x9a, 0xff, 0x39, 0xae, 0x3f, 0x14, 0xb8,
	0x99, 0xaa, 0x48, 0xf6, 0x4e, 0xf8, 0xc4, 0x63, 0xf4, 0xe9, 0x89, 0x24, 0x7f, 0x2d, 0xd8, 0x71,
	0xf1, 0x96, 0xc5, 0x62, 0x5d, 0xed, 0x26, 0x77, 0x25, 0xe5, 0x9d, 0x35, 0xd6, 0x8c, 0x05, 0x8d,
	0x09, 0x54, 0xe2, 0x0f, 0x09, 0x35, 0xe5, 0x75, 0xa5, 0xf2, 0xba, 0xca, 0x6e, 0xb1, 0x05, 0x19,
	0xab, 0x44, 0xb5, 0x35, 0xa0, 0x1e, 0x39, 0x14, 0x26, 0x89, 0xfb, 0xd5, 0xc6, 0x15, 0x84, 0xb5,
	0xb1, 0xab, 0x92, 0x7f, 0x5b, 0x76, 0xc6, 0x16, 0x16, 0xbe, 0x11, 0x50, 0x5c, 0x71, 0x5c, 0xb1,
	0x8a, 0x8b, 0x9a, 0x93, 0xb4, 0x00, 0xdc, 0x4d, 0x84, 0x84, 0xcf, 0xd7, 0x62, 0xd1, 0xc6, 0x56,
	0x2a, 0x64, 0x6c, 0xca, 0x2e, 0xa6, 0xa6, 0x6c, 0x3e, 0x3d, 0xb3, 0xed, 0x55, 0x3c, 0xe0, 0x85,
	0x2b, 0x12, 0x06, 0x15, 0x0a, 0x84, 0x9d, 0x72, 0xb4, 0xb0, 0x87, 0x30, 0x70, 0x10, 0xf8, 0x8a,
	0xbd, 0x4b, 0xee, 0x65, 0x26, 0x7d, 0xd1, 0x42, 0x7a, 0x62, 0x1b, 0x4e, 0x2e, 0xc6, 0x62, 0xd8,
	0x5f, 0x2f, 0xf3, 0x8f, 0xe1, 0x46, 0xca, 0x80, 0x81, 0x2b, 0x64, 0x17, 0x9d, 0xdb, 0xf0, 0x9f,
	0x82, 0xfc, 0x96, 0x65, 0xcd, 0xca, 0x40, 0xee, 0xf4, 0xdf, 0x8e, 0x39, 0xae, 0x72, 0x8e, 0xdf,
	0x91, 0xf0, 0x25, 0x6b, 0x66, 0x9d, 0xde, 0x9f, 0xe5, 0xd0, 0x9b, 0x0d, 0xf7, 0xa9, 0x66, 0xaf,
	0xe4, 0x8c, 0xdd, 0x2a, 0xab, 0x84, 0x44, 0x0d, 0x58, 0xbc, 0x2a, 0x6a, 0x85, 0xfb, 0x5b, 0x47,
	0xca, 0x73, 0xe5, 0xc2, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x3d, 0xdc, 0x98, 0x8f, 0x11,
	0x00, 0x00,
}
