// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gcsystemmsgs.proto

package dota

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type EGCSystemMsg int32

const (
	EGCSystemMsg_k_EGCMsgInvalid                                  EGCSystemMsg = 0
	EGCSystemMsg_k_EGCMsgMulti                                    EGCSystemMsg = 1
	EGCSystemMsg_k_EGCMsgGenericReply                             EGCSystemMsg = 10
	EGCSystemMsg_k_EGCMsgSystemBase                               EGCSystemMsg = 50
	EGCSystemMsg_k_EGCMsgAchievementAwarded                       EGCSystemMsg = 51
	EGCSystemMsg_k_EGCMsgConCommand                               EGCSystemMsg = 52
	EGCSystemMsg_k_EGCMsgStartPlaying                             EGCSystemMsg = 53
	EGCSystemMsg_k_EGCMsgStopPlaying                              EGCSystemMsg = 54
	EGCSystemMsg_k_EGCMsgStartGameserver                          EGCSystemMsg = 55
	EGCSystemMsg_k_EGCMsgStopGameserver                           EGCSystemMsg = 56
	EGCSystemMsg_k_EGCMsgWGRequest                                EGCSystemMsg = 57
	EGCSystemMsg_k_EGCMsgWGResponse                               EGCSystemMsg = 58
	EGCSystemMsg_k_EGCMsgGetUserGameStatsSchema                   EGCSystemMsg = 59
	EGCSystemMsg_k_EGCMsgGetUserGameStatsSchemaResponse           EGCSystemMsg = 60
	EGCSystemMsg_k_EGCMsgGetUserStatsDEPRECATED                   EGCSystemMsg = 61
	EGCSystemMsg_k_EGCMsgGetUserStatsResponse                     EGCSystemMsg = 62
	EGCSystemMsg_k_EGCMsgAppInfoUpdated                           EGCSystemMsg = 63
	EGCSystemMsg_k_EGCMsgValidateSession                          EGCSystemMsg = 64
	EGCSystemMsg_k_EGCMsgValidateSessionResponse                  EGCSystemMsg = 65
	EGCSystemMsg_k_EGCMsgLookupAccountFromInput                   EGCSystemMsg = 66
	EGCSystemMsg_k_EGCMsgSendHTTPRequest                          EGCSystemMsg = 67
	EGCSystemMsg_k_EGCMsgSendHTTPRequestResponse                  EGCSystemMsg = 68
	EGCSystemMsg_k_EGCMsgPreTestSetup                             EGCSystemMsg = 69
	EGCSystemMsg_k_EGCMsgRecordSupportAction                      EGCSystemMsg = 70
	EGCSystemMsg_k_EGCMsgGetAccountDetails_DEPRECATED             EGCSystemMsg = 71
	EGCSystemMsg_k_EGCMsgReceiveInterAppMessage                   EGCSystemMsg = 73
	EGCSystemMsg_k_EGCMsgFindAccounts                             EGCSystemMsg = 74
	EGCSystemMsg_k_EGCMsgPostAlert                                EGCSystemMsg = 75
	EGCSystemMsg_k_EGCMsgGetLicenses                              EGCSystemMsg = 76
	EGCSystemMsg_k_EGCMsgGetUserStats                             EGCSystemMsg = 77
	EGCSystemMsg_k_EGCMsgGetCommands                              EGCSystemMsg = 78
	EGCSystemMsg_k_EGCMsgGetCommandsResponse                      EGCSystemMsg = 79
	EGCSystemMsg_k_EGCMsgAddFreeLicense                           EGCSystemMsg = 80
	EGCSystemMsg_k_EGCMsgAddFreeLicenseResponse                   EGCSystemMsg = 81
	EGCSystemMsg_k_EGCMsgGetIPLocation                            EGCSystemMsg = 82
	EGCSystemMsg_k_EGCMsgGetIPLocationResponse                    EGCSystemMsg = 83
	EGCSystemMsg_k_EGCMsgSystemStatsSchema                        EGCSystemMsg = 84
	EGCSystemMsg_k_EGCMsgGetSystemStats                           EGCSystemMsg = 85
	EGCSystemMsg_k_EGCMsgGetSystemStatsResponse                   EGCSystemMsg = 86
	EGCSystemMsg_k_EGCMsgSendEmail                                EGCSystemMsg = 87
	EGCSystemMsg_k_EGCMsgSendEmailResponse                        EGCSystemMsg = 88
	EGCSystemMsg_k_EGCMsgGetEmailTemplate                         EGCSystemMsg = 89
	EGCSystemMsg_k_EGCMsgGetEmailTemplateResponse                 EGCSystemMsg = 90
	EGCSystemMsg_k_EGCMsgGrantGuestPass                           EGCSystemMsg = 91
	EGCSystemMsg_k_EGCMsgGrantGuestPassResponse                   EGCSystemMsg = 92
	EGCSystemMsg_k_EGCMsgGetAccountDetails                        EGCSystemMsg = 93
	EGCSystemMsg_k_EGCMsgGetAccountDetailsResponse                EGCSystemMsg = 94
	EGCSystemMsg_k_EGCMsgGetPersonaNames                          EGCSystemMsg = 95
	EGCSystemMsg_k_EGCMsgGetPersonaNamesResponse                  EGCSystemMsg = 96
	EGCSystemMsg_k_EGCMsgMultiplexMsg                             EGCSystemMsg = 97
	EGCSystemMsg_k_EGCMsgWebAPIRegisterInterfaces                 EGCSystemMsg = 101
	EGCSystemMsg_k_EGCMsgWebAPIJobRequest                         EGCSystemMsg = 102
	EGCSystemMsg_k_EGCMsgWebAPIJobRequestHttpResponse             EGCSystemMsg = 104
	EGCSystemMsg_k_EGCMsgWebAPIJobRequestForwardResponse          EGCSystemMsg = 105
	EGCSystemMsg_k_EGCMsgMemCachedGet                             EGCSystemMsg = 200
	EGCSystemMsg_k_EGCMsgMemCachedGetResponse                     EGCSystemMsg = 201
	EGCSystemMsg_k_EGCMsgMemCachedSet                             EGCSystemMsg = 202
	EGCSystemMsg_k_EGCMsgMemCachedDelete                          EGCSystemMsg = 203
	EGCSystemMsg_k_EGCMsgMemCachedStats                           EGCSystemMsg = 204
	EGCSystemMsg_k_EGCMsgMemCachedStatsResponse                   EGCSystemMsg = 205
	EGCSystemMsg_k_EGCMsgSQLStats                                 EGCSystemMsg = 210
	EGCSystemMsg_k_EGCMsgSQLStatsResponse                         EGCSystemMsg = 211
	EGCSystemMsg_k_EGCMsgMasterSetDirectory                       EGCSystemMsg = 220
	EGCSystemMsg_k_EGCMsgMasterSetDirectoryResponse               EGCSystemMsg = 221
	EGCSystemMsg_k_EGCMsgMasterSetWebAPIRouting                   EGCSystemMsg = 222
	EGCSystemMsg_k_EGCMsgMasterSetWebAPIRoutingResponse           EGCSystemMsg = 223
	EGCSystemMsg_k_EGCMsgMasterSetClientMsgRouting                EGCSystemMsg = 224
	EGCSystemMsg_k_EGCMsgMasterSetClientMsgRoutingResponse        EGCSystemMsg = 225
	EGCSystemMsg_k_EGCMsgSetOptions                               EGCSystemMsg = 226
	EGCSystemMsg_k_EGCMsgSetOptionsResponse                       EGCSystemMsg = 227
	EGCSystemMsg_k_EGCMsgSystemBase2                              EGCSystemMsg = 500
	EGCSystemMsg_k_EGCMsgGetPurchaseTrustStatus                   EGCSystemMsg = 501
	EGCSystemMsg_k_EGCMsgGetPurchaseTrustStatusResponse           EGCSystemMsg = 502
	EGCSystemMsg_k_EGCMsgUpdateSession                            EGCSystemMsg = 503
	EGCSystemMsg_k_EGCMsgGCAccountVacStatusChange                 EGCSystemMsg = 504
	EGCSystemMsg_k_EGCMsgCheckFriendship                          EGCSystemMsg = 505
	EGCSystemMsg_k_EGCMsgCheckFriendshipResponse                  EGCSystemMsg = 506
	EGCSystemMsg_k_EGCMsgGetPartnerAccountLink                    EGCSystemMsg = 507
	EGCSystemMsg_k_EGCMsgGetPartnerAccountLinkResponse            EGCSystemMsg = 508
	EGCSystemMsg_k_EGCMsgVSReportedSuspiciousActivity             EGCSystemMsg = 509
	EGCSystemMsg_k_EGCMsgDPPartnerMicroTxns                       EGCSystemMsg = 512
	EGCSystemMsg_k_EGCMsgDPPartnerMicroTxnsResponse               EGCSystemMsg = 513
	EGCSystemMsg_k_EGCMsgGetIPASN                                 EGCSystemMsg = 514
	EGCSystemMsg_k_EGCMsgGetIPASNResponse                         EGCSystemMsg = 515
	EGCSystemMsg_k_EGCMsgGetAppFriendsList                        EGCSystemMsg = 516
	EGCSystemMsg_k_EGCMsgGetAppFriendsListResponse                EGCSystemMsg = 517
	EGCSystemMsg_k_EGCMsgVacVerificationChange                    EGCSystemMsg = 518
	EGCSystemMsg_k_EGCMsgAccountPhoneNumberChange                 EGCSystemMsg = 519
	EGCSystemMsg_k_EGCMsgAccountTwoFactorChange                   EGCSystemMsg = 520
	EGCSystemMsg_k_EGCMsgCheckClanMembership                      EGCSystemMsg = 521
	EGCSystemMsg_k_EGCMsgCheckClanMembershipResponse              EGCSystemMsg = 522
	EGCSystemMsg_k_EGCMsgCompressedMsgToClient                    EGCSystemMsg = 523
	EGCSystemMsg_k_EGCMsgGetGamePersonalDataCategoriesRequest     EGCSystemMsg = 524
	EGCSystemMsg_k_EGCMsgGetGamePersonalDataCategoriesResponse    EGCSystemMsg = 525
	EGCSystemMsg_k_EGCMsgGetGamePersonalDataEntriesRequest        EGCSystemMsg = 526
	EGCSystemMsg_k_EGCMsgGetGamePersonalDataEntriesResponse       EGCSystemMsg = 527
	EGCSystemMsg_k_EGCMsgTerminateGamePersonalDataEntriesRequest  EGCSystemMsg = 528
	EGCSystemMsg_k_EGCMsgTerminateGamePersonalDataEntriesResponse EGCSystemMsg = 529
)

var EGCSystemMsg_name = map[int32]string{
	0:   "k_EGCMsgInvalid",
	1:   "k_EGCMsgMulti",
	10:  "k_EGCMsgGenericReply",
	50:  "k_EGCMsgSystemBase",
	51:  "k_EGCMsgAchievementAwarded",
	52:  "k_EGCMsgConCommand",
	53:  "k_EGCMsgStartPlaying",
	54:  "k_EGCMsgStopPlaying",
	55:  "k_EGCMsgStartGameserver",
	56:  "k_EGCMsgStopGameserver",
	57:  "k_EGCMsgWGRequest",
	58:  "k_EGCMsgWGResponse",
	59:  "k_EGCMsgGetUserGameStatsSchema",
	60:  "k_EGCMsgGetUserGameStatsSchemaResponse",
	61:  "k_EGCMsgGetUserStatsDEPRECATED",
	62:  "k_EGCMsgGetUserStatsResponse",
	63:  "k_EGCMsgAppInfoUpdated",
	64:  "k_EGCMsgValidateSession",
	65:  "k_EGCMsgValidateSessionResponse",
	66:  "k_EGCMsgLookupAccountFromInput",
	67:  "k_EGCMsgSendHTTPRequest",
	68:  "k_EGCMsgSendHTTPRequestResponse",
	69:  "k_EGCMsgPreTestSetup",
	70:  "k_EGCMsgRecordSupportAction",
	71:  "k_EGCMsgGetAccountDetails_DEPRECATED",
	73:  "k_EGCMsgReceiveInterAppMessage",
	74:  "k_EGCMsgFindAccounts",
	75:  "k_EGCMsgPostAlert",
	76:  "k_EGCMsgGetLicenses",
	77:  "k_EGCMsgGetUserStats",
	78:  "k_EGCMsgGetCommands",
	79:  "k_EGCMsgGetCommandsResponse",
	80:  "k_EGCMsgAddFreeLicense",
	81:  "k_EGCMsgAddFreeLicenseResponse",
	82:  "k_EGCMsgGetIPLocation",
	83:  "k_EGCMsgGetIPLocationResponse",
	84:  "k_EGCMsgSystemStatsSchema",
	85:  "k_EGCMsgGetSystemStats",
	86:  "k_EGCMsgGetSystemStatsResponse",
	87:  "k_EGCMsgSendEmail",
	88:  "k_EGCMsgSendEmailResponse",
	89:  "k_EGCMsgGetEmailTemplate",
	90:  "k_EGCMsgGetEmailTemplateResponse",
	91:  "k_EGCMsgGrantGuestPass",
	92:  "k_EGCMsgGrantGuestPassResponse",
	93:  "k_EGCMsgGetAccountDetails",
	94:  "k_EGCMsgGetAccountDetailsResponse",
	95:  "k_EGCMsgGetPersonaNames",
	96:  "k_EGCMsgGetPersonaNamesResponse",
	97:  "k_EGCMsgMultiplexMsg",
	101: "k_EGCMsgWebAPIRegisterInterfaces",
	102: "k_EGCMsgWebAPIJobRequest",
	104: "k_EGCMsgWebAPIJobRequestHttpResponse",
	105: "k_EGCMsgWebAPIJobRequestForwardResponse",
	200: "k_EGCMsgMemCachedGet",
	201: "k_EGCMsgMemCachedGetResponse",
	202: "k_EGCMsgMemCachedSet",
	203: "k_EGCMsgMemCachedDelete",
	204: "k_EGCMsgMemCachedStats",
	205: "k_EGCMsgMemCachedStatsResponse",
	210: "k_EGCMsgSQLStats",
	211: "k_EGCMsgSQLStatsResponse",
	220: "k_EGCMsgMasterSetDirectory",
	221: "k_EGCMsgMasterSetDirectoryResponse",
	222: "k_EGCMsgMasterSetWebAPIRouting",
	223: "k_EGCMsgMasterSetWebAPIRoutingResponse",
	224: "k_EGCMsgMasterSetClientMsgRouting",
	225: "k_EGCMsgMasterSetClientMsgRoutingResponse",
	226: "k_EGCMsgSetOptions",
	227: "k_EGCMsgSetOptionsResponse",
	500: "k_EGCMsgSystemBase2",
	501: "k_EGCMsgGetPurchaseTrustStatus",
	502: "k_EGCMsgGetPurchaseTrustStatusResponse",
	503: "k_EGCMsgUpdateSession",
	504: "k_EGCMsgGCAccountVacStatusChange",
	505: "k_EGCMsgCheckFriendship",
	506: "k_EGCMsgCheckFriendshipResponse",
	507: "k_EGCMsgGetPartnerAccountLink",
	508: "k_EGCMsgGetPartnerAccountLinkResponse",
	509: "k_EGCMsgVSReportedSuspiciousActivity",
	512: "k_EGCMsgDPPartnerMicroTxns",
	513: "k_EGCMsgDPPartnerMicroTxnsResponse",
	514: "k_EGCMsgGetIPASN",
	515: "k_EGCMsgGetIPASNResponse",
	516: "k_EGCMsgGetAppFriendsList",
	517: "k_EGCMsgGetAppFriendsListResponse",
	518: "k_EGCMsgVacVerificationChange",
	519: "k_EGCMsgAccountPhoneNumberChange",
	520: "k_EGCMsgAccountTwoFactorChange",
	521: "k_EGCMsgCheckClanMembership",
	522: "k_EGCMsgCheckClanMembershipResponse",
	523: "k_EGCMsgCompressedMsgToClient",
	524: "k_EGCMsgGetGamePersonalDataCategoriesRequest",
	525: "k_EGCMsgGetGamePersonalDataCategoriesResponse",
	526: "k_EGCMsgGetGamePersonalDataEntriesRequest",
	527: "k_EGCMsgGetGamePersonalDataEntriesResponse",
	528: "k_EGCMsgTerminateGamePersonalDataEntriesRequest",
	529: "k_EGCMsgTerminateGamePersonalDataEntriesResponse",
}
var EGCSystemMsg_value = map[string]int32{
	"k_EGCMsgInvalid":                                  0,
	"k_EGCMsgMulti":                                    1,
	"k_EGCMsgGenericReply":                             10,
	"k_EGCMsgSystemBase":                               50,
	"k_EGCMsgAchievementAwarded":                       51,
	"k_EGCMsgConCommand":                               52,
	"k_EGCMsgStartPlaying":                             53,
	"k_EGCMsgStopPlaying":                              54,
	"k_EGCMsgStartGameserver":                          55,
	"k_EGCMsgStopGameserver":                           56,
	"k_EGCMsgWGRequest":                                57,
	"k_EGCMsgWGResponse":                               58,
	"k_EGCMsgGetUserGameStatsSchema":                   59,
	"k_EGCMsgGetUserGameStatsSchemaResponse":           60,
	"k_EGCMsgGetUserStatsDEPRECATED":                   61,
	"k_EGCMsgGetUserStatsResponse":                     62,
	"k_EGCMsgAppInfoUpdated":                           63,
	"k_EGCMsgValidateSession":                          64,
	"k_EGCMsgValidateSessionResponse":                  65,
	"k_EGCMsgLookupAccountFromInput":                   66,
	"k_EGCMsgSendHTTPRequest":                          67,
	"k_EGCMsgSendHTTPRequestResponse":                  68,
	"k_EGCMsgPreTestSetup":                             69,
	"k_EGCMsgRecordSupportAction":                      70,
	"k_EGCMsgGetAccountDetails_DEPRECATED":             71,
	"k_EGCMsgReceiveInterAppMessage":                   73,
	"k_EGCMsgFindAccounts":                             74,
	"k_EGCMsgPostAlert":                                75,
	"k_EGCMsgGetLicenses":                              76,
	"k_EGCMsgGetUserStats":                             77,
	"k_EGCMsgGetCommands":                              78,
	"k_EGCMsgGetCommandsResponse":                      79,
	"k_EGCMsgAddFreeLicense":                           80,
	"k_EGCMsgAddFreeLicenseResponse":                   81,
	"k_EGCMsgGetIPLocation":                            82,
	"k_EGCMsgGetIPLocationResponse":                    83,
	"k_EGCMsgSystemStatsSchema":                        84,
	"k_EGCMsgGetSystemStats":                           85,
	"k_EGCMsgGetSystemStatsResponse":                   86,
	"k_EGCMsgSendEmail":                                87,
	"k_EGCMsgSendEmailResponse":                        88,
	"k_EGCMsgGetEmailTemplate":                         89,
	"k_EGCMsgGetEmailTemplateResponse":                 90,
	"k_EGCMsgGrantGuestPass":                           91,
	"k_EGCMsgGrantGuestPassResponse":                   92,
	"k_EGCMsgGetAccountDetails":                        93,
	"k_EGCMsgGetAccountDetailsResponse":                94,
	"k_EGCMsgGetPersonaNames":                          95,
	"k_EGCMsgGetPersonaNamesResponse":                  96,
	"k_EGCMsgMultiplexMsg":                             97,
	"k_EGCMsgWebAPIRegisterInterfaces":                 101,
	"k_EGCMsgWebAPIJobRequest":                         102,
	"k_EGCMsgWebAPIJobRequestHttpResponse":             104,
	"k_EGCMsgWebAPIJobRequestForwardResponse":          105,
	"k_EGCMsgMemCachedGet":                             200,
	"k_EGCMsgMemCachedGetResponse":                     201,
	"k_EGCMsgMemCachedSet":                             202,
	"k_EGCMsgMemCachedDelete":                          203,
	"k_EGCMsgMemCachedStats":                           204,
	"k_EGCMsgMemCachedStatsResponse":                   205,
	"k_EGCMsgSQLStats":                                 210,
	"k_EGCMsgSQLStatsResponse":                         211,
	"k_EGCMsgMasterSetDirectory":                       220,
	"k_EGCMsgMasterSetDirectoryResponse":               221,
	"k_EGCMsgMasterSetWebAPIRouting":                   222,
	"k_EGCMsgMasterSetWebAPIRoutingResponse":           223,
	"k_EGCMsgMasterSetClientMsgRouting":                224,
	"k_EGCMsgMasterSetClientMsgRoutingResponse":        225,
	"k_EGCMsgSetOptions":                               226,
	"k_EGCMsgSetOptionsResponse":                       227,
	"k_EGCMsgSystemBase2":                              500,
	"k_EGCMsgGetPurchaseTrustStatus":                   501,
	"k_EGCMsgGetPurchaseTrustStatusResponse":           502,
	"k_EGCMsgUpdateSession":                            503,
	"k_EGCMsgGCAccountVacStatusChange":                 504,
	"k_EGCMsgCheckFriendship":                          505,
	"k_EGCMsgCheckFriendshipResponse":                  506,
	"k_EGCMsgGetPartnerAccountLink":                    507,
	"k_EGCMsgGetPartnerAccountLinkResponse":            508,
	"k_EGCMsgVSReportedSuspiciousActivity":             509,
	"k_EGCMsgDPPartnerMicroTxns":                       512,
	"k_EGCMsgDPPartnerMicroTxnsResponse":               513,
	"k_EGCMsgGetIPASN":                                 514,
	"k_EGCMsgGetIPASNResponse":                         515,
	"k_EGCMsgGetAppFriendsList":                        516,
	"k_EGCMsgGetAppFriendsListResponse":                517,
	"k_EGCMsgVacVerificationChange":                    518,
	"k_EGCMsgAccountPhoneNumberChange":                 519,
	"k_EGCMsgAccountTwoFactorChange":                   520,
	"k_EGCMsgCheckClanMembership":                      521,
	"k_EGCMsgCheckClanMembershipResponse":              522,
	"k_EGCMsgCompressedMsgToClient":                    523,
	"k_EGCMsgGetGamePersonalDataCategoriesRequest":     524,
	"k_EGCMsgGetGamePersonalDataCategoriesResponse":    525,
	"k_EGCMsgGetGamePersonalDataEntriesRequest":        526,
	"k_EGCMsgGetGamePersonalDataEntriesResponse":       527,
	"k_EGCMsgTerminateGamePersonalDataEntriesRequest":  528,
	"k_EGCMsgTerminateGamePersonalDataEntriesResponse": 529,
}

func (x EGCSystemMsg) Enum() *EGCSystemMsg {
	p := new(EGCSystemMsg)
	*p = x
	return p
}
func (x EGCSystemMsg) String() string {
	return proto.EnumName(EGCSystemMsg_name, int32(x))
}
func (x *EGCSystemMsg) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EGCSystemMsg_value, data, "EGCSystemMsg")
	if err != nil {
		return err
	}
	*x = EGCSystemMsg(value)
	return nil
}
func (EGCSystemMsg) EnumDescriptor() ([]byte, []int) { return fileDescriptor30, []int{0} }

type ESOMsg int32

const (
	ESOMsg_k_ESOMsg_Create                   ESOMsg = 21
	ESOMsg_k_ESOMsg_Update                   ESOMsg = 22
	ESOMsg_k_ESOMsg_Destroy                  ESOMsg = 23
	ESOMsg_k_ESOMsg_CacheSubscribed          ESOMsg = 24
	ESOMsg_k_ESOMsg_CacheUnsubscribed        ESOMsg = 25
	ESOMsg_k_ESOMsg_UpdateMultiple           ESOMsg = 26
	ESOMsg_k_ESOMsg_CacheSubscriptionRefresh ESOMsg = 28
	ESOMsg_k_ESOMsg_CacheSubscribedUpToDate  ESOMsg = 29
)

var ESOMsg_name = map[int32]string{
	21: "k_ESOMsg_Create",
	22: "k_ESOMsg_Update",
	23: "k_ESOMsg_Destroy",
	24: "k_ESOMsg_CacheSubscribed",
	25: "k_ESOMsg_CacheUnsubscribed",
	26: "k_ESOMsg_UpdateMultiple",
	28: "k_ESOMsg_CacheSubscriptionRefresh",
	29: "k_ESOMsg_CacheSubscribedUpToDate",
}
var ESOMsg_value = map[string]int32{
	"k_ESOMsg_Create":                   21,
	"k_ESOMsg_Update":                   22,
	"k_ESOMsg_Destroy":                  23,
	"k_ESOMsg_CacheSubscribed":          24,
	"k_ESOMsg_CacheUnsubscribed":        25,
	"k_ESOMsg_UpdateMultiple":           26,
	"k_ESOMsg_CacheSubscriptionRefresh": 28,
	"k_ESOMsg_CacheSubscribedUpToDate":  29,
}

func (x ESOMsg) Enum() *ESOMsg {
	p := new(ESOMsg)
	*p = x
	return p
}
func (x ESOMsg) String() string {
	return proto.EnumName(ESOMsg_name, int32(x))
}
func (x *ESOMsg) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ESOMsg_value, data, "ESOMsg")
	if err != nil {
		return err
	}
	*x = ESOMsg(value)
	return nil
}
func (ESOMsg) EnumDescriptor() ([]byte, []int) { return fileDescriptor30, []int{1} }

type EGCBaseClientMsg int32

const (
	EGCBaseClientMsg_k_EMsgGCPingRequest                EGCBaseClientMsg = 3001
	EGCBaseClientMsg_k_EMsgGCPingResponse               EGCBaseClientMsg = 3002
	EGCBaseClientMsg_k_EMsgGCToClientPollConvarRequest  EGCBaseClientMsg = 3003
	EGCBaseClientMsg_k_EMsgGCToClientPollConvarResponse EGCBaseClientMsg = 3004
	EGCBaseClientMsg_k_EMsgGCClientWelcome              EGCBaseClientMsg = 4004
	EGCBaseClientMsg_k_EMsgGCServerWelcome              EGCBaseClientMsg = 4005
	EGCBaseClientMsg_k_EMsgGCClientHello                EGCBaseClientMsg = 4006
	EGCBaseClientMsg_k_EMsgGCServerHello                EGCBaseClientMsg = 4007
	EGCBaseClientMsg_k_EMsgGCClientConnectionStatus     EGCBaseClientMsg = 4009
	EGCBaseClientMsg_k_EMsgGCServerConnectionStatus     EGCBaseClientMsg = 4010
)

var EGCBaseClientMsg_name = map[int32]string{
	3001: "k_EMsgGCPingRequest",
	3002: "k_EMsgGCPingResponse",
	3003: "k_EMsgGCToClientPollConvarRequest",
	3004: "k_EMsgGCToClientPollConvarResponse",
	4004: "k_EMsgGCClientWelcome",
	4005: "k_EMsgGCServerWelcome",
	4006: "k_EMsgGCClientHello",
	4007: "k_EMsgGCServerHello",
	4009: "k_EMsgGCClientConnectionStatus",
	4010: "k_EMsgGCServerConnectionStatus",
}
var EGCBaseClientMsg_value = map[string]int32{
	"k_EMsgGCPingRequest":                3001,
	"k_EMsgGCPingResponse":               3002,
	"k_EMsgGCToClientPollConvarRequest":  3003,
	"k_EMsgGCToClientPollConvarResponse": 3004,
	"k_EMsgGCClientWelcome":              4004,
	"k_EMsgGCServerWelcome":              4005,
	"k_EMsgGCClientHello":                4006,
	"k_EMsgGCServerHello":                4007,
	"k_EMsgGCClientConnectionStatus":     4009,
	"k_EMsgGCServerConnectionStatus":     4010,
}

func (x EGCBaseClientMsg) Enum() *EGCBaseClientMsg {
	p := new(EGCBaseClientMsg)
	*p = x
	return p
}
func (x EGCBaseClientMsg) String() string {
	return proto.EnumName(EGCBaseClientMsg_name, int32(x))
}
func (x *EGCBaseClientMsg) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EGCBaseClientMsg_value, data, "EGCBaseClientMsg")
	if err != nil {
		return err
	}
	*x = EGCBaseClientMsg(value)
	return nil
}
func (EGCBaseClientMsg) EnumDescriptor() ([]byte, []int) { return fileDescriptor30, []int{2} }

type EGCToGCMsg int32

const (
	EGCToGCMsg_k_EGCToGCMsgMasterAck                      EGCToGCMsg = 150
	EGCToGCMsg_k_EGCToGCMsgMasterAckResponse              EGCToGCMsg = 151
	EGCToGCMsg_k_EGCToGCMsgRouted                         EGCToGCMsg = 152
	EGCToGCMsg_k_EGCToGCMsgRoutedReply                    EGCToGCMsg = 153
	EGCToGCMsg_k_EMsgGCUpdateSubGCSessionInfo             EGCToGCMsg = 154
	EGCToGCMsg_k_EMsgGCRequestSubGCSessionInfo            EGCToGCMsg = 155
	EGCToGCMsg_k_EMsgGCRequestSubGCSessionInfoResponse    EGCToGCMsg = 156
	EGCToGCMsg_k_EGCToGCMsgMasterStartupComplete          EGCToGCMsg = 157
	EGCToGCMsg_k_EMsgGCToGCSOCacheSubscribe               EGCToGCMsg = 158
	EGCToGCMsg_k_EMsgGCToGCSOCacheUnsubscribe             EGCToGCMsg = 159
	EGCToGCMsg_k_EMsgGCToGCLoadSessionSOCache             EGCToGCMsg = 160
	EGCToGCMsg_k_EMsgGCToGCLoadSessionSOCacheResponse     EGCToGCMsg = 161
	EGCToGCMsg_k_EMsgGCToGCUpdateSessionStats             EGCToGCMsg = 162
	EGCToGCMsg_k_EMsgGCToGCUniverseStartup                EGCToGCMsg = 163
	EGCToGCMsg_k_EMsgGCToGCUniverseStartupResponse        EGCToGCMsg = 164
	EGCToGCMsg_k_EMsgGCToGCForwardAccountDetails          EGCToGCMsg = 165
	EGCToGCMsg_k_EMsgGCToGCMasterBroadcastMessage         EGCToGCMsg = 166
	EGCToGCMsg_k_EMsgGCToGCMasterSubscribeToCache         EGCToGCMsg = 167
	EGCToGCMsg_k_EMsgGCToGCMasterSubscribeToCacheResponse EGCToGCMsg = 168
	EGCToGCMsg_k_EMsgGCToGCMasterUnsubscribeFromCache     EGCToGCMsg = 169
	EGCToGCMsg_k_EMsgGCToGCMasterDestroyCache             EGCToGCMsg = 170
)

var EGCToGCMsg_name = map[int32]string{
	150: "k_EGCToGCMsgMasterAck",
	151: "k_EGCToGCMsgMasterAckResponse",
	152: "k_EGCToGCMsgRouted",
	153: "k_EGCToGCMsgRoutedReply",
	154: "k_EMsgGCUpdateSubGCSessionInfo",
	155: "k_EMsgGCRequestSubGCSessionInfo",
	156: "k_EMsgGCRequestSubGCSessionInfoResponse",
	157: "k_EGCToGCMsgMasterStartupComplete",
	158: "k_EMsgGCToGCSOCacheSubscribe",
	159: "k_EMsgGCToGCSOCacheUnsubscribe",
	160: "k_EMsgGCToGCLoadSessionSOCache",
	161: "k_EMsgGCToGCLoadSessionSOCacheResponse",
	162: "k_EMsgGCToGCUpdateSessionStats",
	163: "k_EMsgGCToGCUniverseStartup",
	164: "k_EMsgGCToGCUniverseStartupResponse",
	165: "k_EMsgGCToGCForwardAccountDetails",
	166: "k_EMsgGCToGCMasterBroadcastMessage",
	167: "k_EMsgGCToGCMasterSubscribeToCache",
	168: "k_EMsgGCToGCMasterSubscribeToCacheResponse",
	169: "k_EMsgGCToGCMasterUnsubscribeFromCache",
	170: "k_EMsgGCToGCMasterDestroyCache",
}
var EGCToGCMsg_value = map[string]int32{
	"k_EGCToGCMsgMasterAck":                      150,
	"k_EGCToGCMsgMasterAckResponse":              151,
	"k_EGCToGCMsgRouted":                         152,
	"k_EGCToGCMsgRoutedReply":                    153,
	"k_EMsgGCUpdateSubGCSessionInfo":             154,
	"k_EMsgGCRequestSubGCSessionInfo":            155,
	"k_EMsgGCRequestSubGCSessionInfoResponse":    156,
	"k_EGCToGCMsgMasterStartupComplete":          157,
	"k_EMsgGCToGCSOCacheSubscribe":               158,
	"k_EMsgGCToGCSOCacheUnsubscribe":             159,
	"k_EMsgGCToGCLoadSessionSOCache":             160,
	"k_EMsgGCToGCLoadSessionSOCacheResponse":     161,
	"k_EMsgGCToGCUpdateSessionStats":             162,
	"k_EMsgGCToGCUniverseStartup":                163,
	"k_EMsgGCToGCUniverseStartupResponse":        164,
	"k_EMsgGCToGCForwardAccountDetails":          165,
	"k_EMsgGCToGCMasterBroadcastMessage":         166,
	"k_EMsgGCToGCMasterSubscribeToCache":         167,
	"k_EMsgGCToGCMasterSubscribeToCacheResponse": 168,
	"k_EMsgGCToGCMasterUnsubscribeFromCache":     169,
	"k_EMsgGCToGCMasterDestroyCache":             170,
}

func (x EGCToGCMsg) Enum() *EGCToGCMsg {
	p := new(EGCToGCMsg)
	*p = x
	return p
}
func (x EGCToGCMsg) String() string {
	return proto.EnumName(EGCToGCMsg_name, int32(x))
}
func (x *EGCToGCMsg) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EGCToGCMsg_value, data, "EGCToGCMsg")
	if err != nil {
		return err
	}
	*x = EGCToGCMsg(value)
	return nil
}
func (EGCToGCMsg) EnumDescriptor() ([]byte, []int) { return fileDescriptor30, []int{3} }

type CCommunity_GamePersonalDataCategoryInfo struct {
	Type                      *string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	TypeLocalizationToken     *string `protobuf:"bytes,2,opt,name=type_localization_token,json=typeLocalizationToken" json:"type_localization_token,omitempty"`
	TemplateFile              *string `protobuf:"bytes,3,opt,name=template_file,json=templateFile" json:"template_file,omitempty"`
	Category                  *string `protobuf:"bytes,4,opt,name=category" json:"category,omitempty"`
	CategoryLocalizationToken *string `protobuf:"bytes,5,opt,name=category_localization_token,json=categoryLocalizationToken" json:"category_localization_token,omitempty"`
	XXX_unrecognized          []byte  `json:"-"`
}

func (m *CCommunity_GamePersonalDataCategoryInfo) Reset() {
	*m = CCommunity_GamePersonalDataCategoryInfo{}
}
func (m *CCommunity_GamePersonalDataCategoryInfo) String() string { return proto.CompactTextString(m) }
func (*CCommunity_GamePersonalDataCategoryInfo) ProtoMessage()    {}
func (*CCommunity_GamePersonalDataCategoryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor30, []int{0}
}

func (m *CCommunity_GamePersonalDataCategoryInfo) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *CCommunity_GamePersonalDataCategoryInfo) GetTypeLocalizationToken() string {
	if m != nil && m.TypeLocalizationToken != nil {
		return *m.TypeLocalizationToken
	}
	return ""
}

func (m *CCommunity_GamePersonalDataCategoryInfo) GetTemplateFile() string {
	if m != nil && m.TemplateFile != nil {
		return *m.TemplateFile
	}
	return ""
}

func (m *CCommunity_GamePersonalDataCategoryInfo) GetCategory() string {
	if m != nil && m.Category != nil {
		return *m.Category
	}
	return ""
}

func (m *CCommunity_GamePersonalDataCategoryInfo) GetCategoryLocalizationToken() string {
	if m != nil && m.CategoryLocalizationToken != nil {
		return *m.CategoryLocalizationToken
	}
	return ""
}

type CCommunity_GetGamePersonalDataCategories_Request struct {
	Appid            *uint32 `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CCommunity_GetGamePersonalDataCategories_Request) Reset() {
	*m = CCommunity_GetGamePersonalDataCategories_Request{}
}
func (m *CCommunity_GetGamePersonalDataCategories_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CCommunity_GetGamePersonalDataCategories_Request) ProtoMessage() {}
func (*CCommunity_GetGamePersonalDataCategories_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor30, []int{1}
}

func (m *CCommunity_GetGamePersonalDataCategories_Request) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

type CCommunity_GetGamePersonalDataCategories_Response struct {
	Categories        []*CCommunity_GamePersonalDataCategoryInfo `protobuf:"bytes,1,rep,name=categories" json:"categories,omitempty"`
	AppAssetsBasename *string                                    `protobuf:"bytes,2,opt,name=app_assets_basename,json=appAssetsBasename" json:"app_assets_basename,omitempty"`
	XXX_unrecognized  []byte                                     `json:"-"`
}

func (m *CCommunity_GetGamePersonalDataCategories_Response) Reset() {
	*m = CCommunity_GetGamePersonalDataCategories_Response{}
}
func (m *CCommunity_GetGamePersonalDataCategories_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CCommunity_GetGamePersonalDataCategories_Response) ProtoMessage() {}
func (*CCommunity_GetGamePersonalDataCategories_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor30, []int{2}
}

func (m *CCommunity_GetGamePersonalDataCategories_Response) GetCategories() []*CCommunity_GamePersonalDataCategoryInfo {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *CCommunity_GetGamePersonalDataCategories_Response) GetAppAssetsBasename() string {
	if m != nil && m.AppAssetsBasename != nil {
		return *m.AppAssetsBasename
	}
	return ""
}

type CCommunity_GetGamePersonalDataEntries_Request struct {
	Appid            *uint32 `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	Steamid          *uint64 `protobuf:"varint,2,opt,name=steamid" json:"steamid,omitempty"`
	Type             *string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	ContinueToken    *string `protobuf:"bytes,4,opt,name=continue_token,json=continueToken" json:"continue_token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CCommunity_GetGamePersonalDataEntries_Request) Reset() {
	*m = CCommunity_GetGamePersonalDataEntries_Request{}
}
func (m *CCommunity_GetGamePersonalDataEntries_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CCommunity_GetGamePersonalDataEntries_Request) ProtoMessage() {}
func (*CCommunity_GetGamePersonalDataEntries_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor30, []int{3}
}

func (m *CCommunity_GetGamePersonalDataEntries_Request) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

func (m *CCommunity_GetGamePersonalDataEntries_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CCommunity_GetGamePersonalDataEntries_Request) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *CCommunity_GetGamePersonalDataEntries_Request) GetContinueToken() string {
	if m != nil && m.ContinueToken != nil {
		return *m.ContinueToken
	}
	return ""
}

type CCommunity_GetGamePersonalDataEntries_Response struct {
	Gceresult        *uint32  `protobuf:"varint,1,opt,name=gceresult" json:"gceresult,omitempty"`
	Entries          []string `protobuf:"bytes,2,rep,name=entries" json:"entries,omitempty"`
	ContinueToken    *string  `protobuf:"bytes,3,opt,name=continue_token,json=continueToken" json:"continue_token,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CCommunity_GetGamePersonalDataEntries_Response) Reset() {
	*m = CCommunity_GetGamePersonalDataEntries_Response{}
}
func (m *CCommunity_GetGamePersonalDataEntries_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CCommunity_GetGamePersonalDataEntries_Response) ProtoMessage() {}
func (*CCommunity_GetGamePersonalDataEntries_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor30, []int{4}
}

func (m *CCommunity_GetGamePersonalDataEntries_Response) GetGceresult() uint32 {
	if m != nil && m.Gceresult != nil {
		return *m.Gceresult
	}
	return 0
}

func (m *CCommunity_GetGamePersonalDataEntries_Response) GetEntries() []string {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *CCommunity_GetGamePersonalDataEntries_Response) GetContinueToken() string {
	if m != nil && m.ContinueToken != nil {
		return *m.ContinueToken
	}
	return ""
}

type CCommunity_TerminateGamePersonalDataEntries_Request struct {
	Appid            *uint32 `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	Steamid          *uint64 `protobuf:"varint,2,opt,name=steamid" json:"steamid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CCommunity_TerminateGamePersonalDataEntries_Request) Reset() {
	*m = CCommunity_TerminateGamePersonalDataEntries_Request{}
}
func (m *CCommunity_TerminateGamePersonalDataEntries_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CCommunity_TerminateGamePersonalDataEntries_Request) ProtoMessage() {}
func (*CCommunity_TerminateGamePersonalDataEntries_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor30, []int{5}
}

func (m *CCommunity_TerminateGamePersonalDataEntries_Request) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

func (m *CCommunity_TerminateGamePersonalDataEntries_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

type CCommunity_TerminateGamePersonalDataEntries_Response struct {
	Gceresult        *uint32 `protobuf:"varint,1,opt,name=gceresult" json:"gceresult,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CCommunity_TerminateGamePersonalDataEntries_Response) Reset() {
	*m = CCommunity_TerminateGamePersonalDataEntries_Response{}
}
func (m *CCommunity_TerminateGamePersonalDataEntries_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CCommunity_TerminateGamePersonalDataEntries_Response) ProtoMessage() {}
func (*CCommunity_TerminateGamePersonalDataEntries_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor30, []int{6}
}

func (m *CCommunity_TerminateGamePersonalDataEntries_Response) GetGceresult() uint32 {
	if m != nil && m.Gceresult != nil {
		return *m.Gceresult
	}
	return 0
}

func init() {
	proto.RegisterType((*CCommunity_GamePersonalDataCategoryInfo)(nil), "dota.CCommunity_GamePersonalDataCategoryInfo")
	proto.RegisterType((*CCommunity_GetGamePersonalDataCategories_Request)(nil), "dota.CCommunity_GetGamePersonalDataCategories_Request")
	proto.RegisterType((*CCommunity_GetGamePersonalDataCategories_Response)(nil), "dota.CCommunity_GetGamePersonalDataCategories_Response")
	proto.RegisterType((*CCommunity_GetGamePersonalDataEntries_Request)(nil), "dota.CCommunity_GetGamePersonalDataEntries_Request")
	proto.RegisterType((*CCommunity_GetGamePersonalDataEntries_Response)(nil), "dota.CCommunity_GetGamePersonalDataEntries_Response")
	proto.RegisterType((*CCommunity_TerminateGamePersonalDataEntries_Request)(nil), "dota.CCommunity_TerminateGamePersonalDataEntries_Request")
	proto.RegisterType((*CCommunity_TerminateGamePersonalDataEntries_Response)(nil), "dota.CCommunity_TerminateGamePersonalDataEntries_Response")
	proto.RegisterEnum("dota.EGCSystemMsg", EGCSystemMsg_name, EGCSystemMsg_value)
	proto.RegisterEnum("dota.ESOMsg", ESOMsg_name, ESOMsg_value)
	proto.RegisterEnum("dota.EGCBaseClientMsg", EGCBaseClientMsg_name, EGCBaseClientMsg_value)
	proto.RegisterEnum("dota.EGCToGCMsg", EGCToGCMsg_name, EGCToGCMsg_value)
}

func init() { proto.RegisterFile("gcsystemmsgs.proto", fileDescriptor30) }

var fileDescriptor30 = []byte{
	// 2087 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x59, 0x77, 0xdb, 0xc6,
	0x15, 0x0e, 0x4c, 0x38, 0xad, 0xa7, 0x71, 0x3b, 0x1e, 0x5b, 0x16, 0x25, 0xcb, 0x96, 0x2c, 0xdb,
	0xb1, 0xa2, 0xc4, 0x4a, 0xe2, 0x38, 0xe9, 0x9e, 0x96, 0x06, 0x29, 0x4a, 0xa9, 0x68, 0x33, 0x24,
	0x25, 0x77, 0x67, 0x47, 0xc0, 0x15, 0x89, 0x23, 0x10, 0x83, 0x62, 0x06, 0x4a, 0xd4, 0xa7, 0x74,
	0xdf, 0x9b, 0xf6, 0xa5, 0x4b, 0xba, 0xb7, 0x59, 0x9a, 0x9c, 0x3e, 0xf5, 0xad, 0xcb, 0x0f, 0xe8,
	0xfe, 0xd0, 0xbe, 0x76, 0xef, 0x1f, 0xe8, 0x43, 0x9b, 0xa6, 0xdb, 0x39, 0x3d, 0x00, 0x06, 0x83,
	0x81, 0x48, 0xca, 0xf2, 0x39, 0x79, 0x22, 0x31, 0xdf, 0x77, 0xef, 0xdc, 0xb9, 0xeb, 0x0c, 0x22,
	0x3d, 0x9b, 0xef, 0x72, 0x01, 0x83, 0x01, 0xef, 0xf1, 0xa5, 0x20, 0x64, 0x82, 0x11, 0xd3, 0x61,
	0x82, 0xce, 0xbf, 0x68, 0xa0, 0x8b, 0x96, 0xc5, 0x06, 0x83, 0xc8, 0x77, 0xc5, 0x6e, 0xb7, 0x4e,
	0x07, 0xd0, 0x84, 0x90, 0x33, 0x9f, 0x7a, 0x55, 0x2a, 0xa8, 0x45, 0x05, 0xf4, 0x58, 0xb8, 0xbb,
	0xea, 0x6f, 0x31, 0x42, 0x90, 0x29, 0x76, 0x03, 0x28, 0x1b, 0x73, 0xc6, 0xc2, 0x91, 0x56, 0xf2,
	0x9f, 0x3c, 0x84, 0x26, 0xe3, 0xdf, 0xae, 0xc7, 0x6c, 0xea, 0xb9, 0x1f, 0xa0, 0xc2, 0x65, 0x7e,
	0x57, 0xb0, 0x6d, 0xf0, 0xcb, 0x87, 0x12, 0xda, 0x44, 0x0c, 0xaf, 0x69, 0x68, 0x27, 0x06, 0xc9,
	0x39, 0x74, 0x54, 0xc0, 0x20, 0xf0, 0xa8, 0x80, 0xee, 0x96, 0xeb, 0x41, 0xb9, 0x94, 0xb0, 0xef,
	0xc8, 0x16, 0x97, 0x5d, 0x0f, 0xc8, 0x34, 0x7a, 0xa5, 0x2d, 0x0d, 0x28, 0x9b, 0x09, 0xae, 0xbe,
	0xc9, 0xc3, 0xe8, 0x54, 0xf6, 0x7f, 0xd4, 0xe6, 0x87, 0x13, 0xfa, 0x54, 0x46, 0x19, 0x32, 0x60,
	0x7e, 0x05, 0xdd, 0xa7, 0x9f, 0x1b, 0xc4, 0x98, 0xa3, 0xbb, 0xc0, 0xbb, 0x2d, 0x78, 0x7f, 0x04,
	0x5c, 0x90, 0x13, 0xe8, 0x30, 0x0d, 0x02, 0xd7, 0x49, 0x3c, 0x70, 0xb4, 0x95, 0x7e, 0xcc, 0xff,
	0xc0, 0x40, 0xf7, 0xdf, 0x82, 0x2a, 0x1e, 0x30, 0x9f, 0x03, 0x69, 0x20, 0x64, 0xab, 0xe5, 0xb2,
	0x31, 0x57, 0x5a, 0x78, 0xd5, 0xe5, 0x4b, 0x4b, 0x71, 0x4c, 0x96, 0x0e, 0x18, 0x8f, 0x96, 0xa6,
	0x80, 0x2c, 0xa1, 0xe3, 0x34, 0x08, 0xba, 0x94, 0x73, 0x10, 0xbc, 0xbb, 0x49, 0x39, 0xf8, 0x74,
	0x00, 0x32, 0x06, 0xc7, 0x68, 0x10, 0x54, 0x12, 0xe4, 0xaa, 0x04, 0xe6, 0x9f, 0x32, 0xd0, 0xa5,
	0xfd, 0x8d, 0xae, 0xf9, 0xe2, 0xe6, 0x87, 0x27, 0x65, 0xf4, 0x0a, 0x2e, 0x80, 0x0e, 0x5c, 0x27,
	0xd9, 0xcb, 0x6c, 0x65, 0x9f, 0x2a, 0x5b, 0x4a, 0x5a, 0xb6, 0x5c, 0x40, 0xaf, 0xb6, 0x99, 0x2f,
	0x5c, 0x3f, 0x02, 0x19, 0xa7, 0x34, 0xac, 0x47, 0xb3, 0xd5, 0x34, 0x36, 0x4f, 0x1a, 0x68, 0xe9,
	0xa0, 0xc6, 0x49, 0x77, 0xce, 0xa0, 0x23, 0x3d, 0x1b, 0x42, 0xe0, 0x91, 0x27, 0xa4, 0x85, 0xf9,
	0x42, 0x6c, 0x25, 0xa4, 0x12, 0xe5, 0x43, 0x73, 0xa5, 0x85, 0x23, 0xad, 0xec, 0x73, 0x84, 0x45,
	0xa5, 0x51, 0x16, 0x01, 0x7a, 0x40, 0x33, 0xa8, 0x03, 0xe1, 0xc0, 0xf5, 0xa9, 0x80, 0x97, 0xd9,
	0x67, 0xf3, 0x1d, 0x74, 0xe5, 0xd6, 0xb6, 0x39, 0xc8, 0xe9, 0x17, 0x5f, 0x9a, 0x42, 0x77, 0xd4,
	0xea, 0x56, 0x3b, 0xe9, 0x00, 0x0d, 0xde, 0x23, 0xc7, 0xd1, 0x6b, 0xb6, 0xbb, 0xb5, 0xba, 0xd5,
	0xe0, 0xbd, 0x55, 0x7f, 0x87, 0x7a, 0xae, 0x83, 0x6f, 0x23, 0xc7, 0xd0, 0xd1, 0x6c, 0xb1, 0x11,
	0x79, 0xc2, 0xc5, 0x06, 0x29, 0xa3, 0x13, 0xd9, 0x52, 0x1d, 0x7c, 0x08, 0x5d, 0xbb, 0x05, 0x81,
	0xb7, 0x8b, 0x11, 0x39, 0x89, 0x48, 0x86, 0xa4, 0x6a, 0xe3, 0xc4, 0xc2, 0x97, 0xc9, 0x19, 0x34,
	0x9d, 0xad, 0x57, 0xec, 0xbe, 0x0b, 0x3b, 0x30, 0x00, 0x5f, 0x54, 0x1e, 0xa3, 0xa1, 0x03, 0x0e,
	0x7e, 0x40, 0x97, 0xb3, 0x98, 0x1f, 0x1f, 0x95, 0xfa, 0x0e, 0xbe, 0xa2, 0xef, 0xd4, 0x16, 0x34,
	0x14, 0x4d, 0x8f, 0xee, 0xba, 0x7e, 0x0f, 0x3f, 0x48, 0x26, 0xd1, 0xf1, 0x1c, 0x61, 0x41, 0x06,
	0x3c, 0x44, 0x4e, 0xa1, 0xc9, 0x82, 0x48, 0xec, 0x24, 0x0e, 0xe1, 0x0e, 0x84, 0xf8, 0xb5, 0x64,
	0x1a, 0x9d, 0xd4, 0xa5, 0x34, 0xec, 0x75, 0x64, 0x02, 0x1d, 0xcb, 0xb0, 0x1b, 0x75, 0x19, 0x29,
	0xfc, 0x7a, 0xdd, 0xb4, 0x78, 0x39, 0xf5, 0x2c, 0x7e, 0x03, 0x99, 0x47, 0x67, 0x72, 0x27, 0x88,
	0x75, 0x0e, 0x61, 0xac, 0xad, 0x2d, 0xa8, 0xe0, 0x6d, 0xbb, 0x0f, 0x03, 0x8a, 0xdf, 0x48, 0x16,
	0xd1, 0x9d, 0xfb, 0x73, 0x94, 0xbe, 0x37, 0x8d, 0xd0, 0x97, 0xf0, 0xaa, 0xb5, 0x66, 0xab, 0x66,
	0x55, 0x3a, 0xb5, 0x2a, 0x7e, 0x33, 0x99, 0x43, 0x33, 0xa3, 0x38, 0x4a, 0xcb, 0xc3, 0xfa, 0x01,
	0x2b, 0x41, 0x10, 0xb7, 0x83, 0xf5, 0xc0, 0xa1, 0x02, 0x1c, 0xfc, 0x16, 0xdd, 0x33, 0x1b, 0x71,
	0x70, 0xa9, 0x80, 0x36, 0x70, 0xee, 0x32, 0x1f, 0xbf, 0x95, 0x9c, 0x43, 0xb3, 0x63, 0x40, 0xa5,
	0xbd, 0xa2, 0xdb, 0xb8, 0xc6, 0xd8, 0x76, 0x14, 0x54, 0x6c, 0x9b, 0x45, 0xbe, 0x58, 0x0e, 0xd9,
	0x60, 0xd5, 0x0f, 0x22, 0x81, 0xaf, 0x16, 0xfc, 0x0f, 0xbe, 0xb3, 0xd2, 0xe9, 0x34, 0x33, 0x67,
	0x5a, 0xfa, 0x2e, 0x7b, 0x40, 0xb5, 0x4b, 0x55, 0x0f, 0x7a, 0x33, 0x84, 0x0e, 0x70, 0xd1, 0x06,
	0x11, 0x05, 0xb8, 0x46, 0x66, 0xd1, 0xa9, 0x0c, 0x69, 0x81, 0xcd, 0x42, 0xa7, 0x1d, 0x05, 0x01,
	0x0b, 0x45, 0xc5, 0x8e, 0x1b, 0x38, 0x5e, 0x26, 0x0b, 0xe8, 0xbc, 0xe6, 0x20, 0x69, 0x5d, 0x15,
	0x04, 0x75, 0x3d, 0xde, 0xd5, 0x5c, 0x59, 0xd7, 0x8f, 0xd2, 0x02, 0x1b, 0xdc, 0x1d, 0x58, 0xf5,
	0x05, 0x84, 0x95, 0x20, 0x68, 0x00, 0xe7, 0xb4, 0x07, 0x78, 0x55, 0x37, 0x64, 0xd9, 0xf5, 0x1d,
	0xa9, 0x8e, 0xe3, 0x47, 0xf4, 0x5c, 0x69, 0x32, 0x2e, 0x2a, 0x1e, 0x84, 0x02, 0xbf, 0x4d, 0x4f,
	0xca, 0x3a, 0x88, 0x35, 0xd7, 0x06, 0x9f, 0x03, 0xc7, 0x6b, 0xc5, 0x8a, 0xc9, 0x03, 0x87, 0x1b,
	0x7b, 0x44, 0x64, 0xe6, 0x73, 0x7c, 0x4d, 0x3f, 0xab, 0x06, 0x28, 0x37, 0x5d, 0x2f, 0x84, 0xda,
	0x71, 0x96, 0x43, 0x00, 0xb9, 0x21, 0x6e, 0xea, 0xa7, 0x2b, 0x62, 0x4a, 0xfe, 0x51, 0x32, 0x85,
	0x26, 0xb4, 0x0d, 0x56, 0x9b, 0xf1, 0x2c, 0x4c, 0xdc, 0xd8, 0x22, 0x67, 0xd1, 0xe9, 0x91, 0x90,
	0x92, 0x6e, 0x93, 0xd3, 0x68, 0xaa, 0x58, 0xe9, 0x7a, 0xe6, 0x77, 0x74, 0xe3, 0xea, 0x20, 0x34,
	0x06, 0x5e, 0xdf, 0x93, 0xe9, 0x1a, 0xa6, 0xd4, 0x6f, 0xe8, 0x0e, 0x8e, 0x13, 0xa5, 0x36, 0xa0,
	0xae, 0x87, 0x6f, 0x14, 0x76, 0xcd, 0x96, 0x95, 0xd4, 0xdb, 0xc9, 0x0c, 0x2a, 0x6b, 0x9a, 0x13,
	0xb4, 0x23, 0x2f, 0x0e, 0xf8, 0x1d, 0xe4, 0x3c, 0x9a, 0x1b, 0x87, 0x2a, 0x1d, 0xef, 0x2c, 0x58,
	0x1e, 0x52, 0x5f, 0xd4, 0xe3, 0xec, 0x6c, 0x52, 0xce, 0xf1, 0xbb, 0x0a, 0x96, 0x17, 0x30, 0x25,
	0xff, 0x6e, 0xdd, 0xc4, 0xa1, 0x14, 0xc4, 0xef, 0x21, 0x17, 0xd0, 0xd9, 0xb1, 0xb0, 0xd2, 0xf2,
	0x5e, 0xbd, 0x8a, 0xea, 0x20, 0x64, 0x93, 0xbf, 0x16, 0xb7, 0x2b, 0xdc, 0xd5, 0xab, 0x68, 0x0f,
	0xa8, 0x34, 0xbc, 0x4f, 0x4f, 0xb9, 0xa4, 0x6f, 0x07, 0x1e, 0x3c, 0xde, 0xe0, 0x3d, 0x4c, 0x75,
	0x3f, 0xdc, 0x80, 0xcd, 0x4a, 0x73, 0xb5, 0x05, 0x3d, 0x97, 0x0b, 0x08, 0x93, 0x0a, 0xd8, 0xa2,
	0x36, 0x70, 0x0c, 0xba, 0x2f, 0x53, 0xd6, 0x23, 0x6c, 0x33, 0x2b, 0xe4, 0x2d, 0xbd, 0xd0, 0xf6,
	0xa2, 0x2b, 0x42, 0x04, 0xca, 0x8e, 0x3e, 0xb9, 0x1b, 0x5d, 0x1c, 0xc7, 0x5c, 0x66, 0x61, 0x3c,
	0x01, 0x14, 0xd9, 0x25, 0x53, 0x9a, 0xd1, 0x30, 0xb0, 0xa8, 0xdd, 0x07, 0xa7, 0x0e, 0x02, 0xff,
	0xd4, 0x20, 0x67, 0xf3, 0xde, 0xa7, 0x43, 0x4a, 0xf8, 0x67, 0xc6, 0x48, 0xe9, 0x36, 0x08, 0xfc,
	0x73, 0x83, 0xcc, 0xe4, 0xfe, 0x54, 0x50, 0x15, 0x3c, 0x10, 0x80, 0x7f, 0x61, 0x90, 0x53, 0x79,
	0xcc, 0x73, 0xc1, 0x24, 0x5b, 0x7f, 0x69, 0x90, 0x73, 0x79, 0xd0, 0x8b, 0xa0, 0xda, 0xfa, 0x57,
	0x06, 0x99, 0x40, 0x58, 0x25, 0xe6, 0xa3, 0x6b, 0xa9, 0xec, 0x6f, 0x0c, 0x72, 0x3a, 0x77, 0x62,
	0xb6, 0xac, 0xa4, 0x7e, 0x6b, 0x90, 0xd9, 0x7c, 0x2c, 0x36, 0x68, 0x1c, 0x81, 0x36, 0x88, 0xaa,
	0x1b, 0x82, 0x2d, 0x58, 0xb8, 0x8b, 0x7f, 0x67, 0x90, 0x8b, 0x68, 0x7e, 0x3c, 0x41, 0x69, 0xfa,
	0x7d, 0xd1, 0xc8, 0x8c, 0x28, 0x83, 0xcb, 0x22, 0x11, 0x4f, 0xc6, 0x3f, 0x18, 0xe4, 0xee, 0x7c,
	0x1c, 0x8d, 0x26, 0x29, 0x8d, 0x7f, 0x34, 0xc8, 0x9d, 0x79, 0xa2, 0x2a, 0xb2, 0xe5, 0xb9, 0xe0,
	0x8b, 0xb8, 0x65, 0x4a, 0xa5, 0x7f, 0x32, 0xc8, 0x12, 0xba, 0xeb, 0xa6, 0x3c, 0xa5, 0xf7, 0xcf,
	0x06, 0x99, 0xd4, 0xae, 0x08, 0x20, 0xae, 0x07, 0x71, 0x5f, 0xe1, 0xf8, 0x2f, 0x05, 0x67, 0xe4,
	0x80, 0x92, 0xfc, 0x6b, 0x7c, 0xed, 0x38, 0x3e, 0x7c, 0xb9, 0xb8, 0x8c, 0xff, 0x5e, 0xd2, 0x4f,
	0x1f, 0x17, 0x44, 0x14, 0xda, 0x7d, 0xca, 0xa1, 0x13, 0x46, 0x5c, 0xc4, 0x3e, 0x8f, 0x38, 0xfe,
	0x47, 0x49, 0x3f, 0xfd, 0x68, 0x92, 0xda, 0xeb, 0xc5, 0x12, 0x99, 0xce, 0x9b, 0x63, 0x3a, 0x40,
	0xb3, 0x49, 0xf9, 0xcf, 0x12, 0xb9, 0xa0, 0xf5, 0x11, 0x4b, 0x56, 0xf0, 0x06, 0xb5, 0x53, 0x25,
	0x56, 0x9f, 0xfa, 0x3d, 0xc0, 0x2f, 0x95, 0xf4, 0x94, 0xb3, 0xfa, 0x60, 0x6f, 0x2f, 0x87, 0x2e,
	0xf8, 0x0e, 0xef, 0xbb, 0x01, 0xfe, 0x57, 0x89, 0x9c, 0xcf, 0x6b, 0x78, 0x0f, 0xaa, 0xcc, 0xf8,
	0x77, 0x89, 0xcc, 0x17, 0x1a, 0x71, 0x93, 0x86, 0xc2, 0x87, 0x50, 0x6e, 0xb9, 0xe6, 0xfa, 0xdb,
	0xf8, 0x3f, 0x25, 0xb2, 0x88, 0x2e, 0xec, 0xcb, 0x51, 0xfa, 0xfe, 0x5b, 0x22, 0x77, 0xe5, 0x65,
	0xbb, 0xd1, 0x6e, 0x41, 0x3c, 0x3b, 0xc1, 0x69, 0x47, 0x3c, 0x70, 0x6d, 0x97, 0x45, 0x3c, 0x9e,
	0xa3, 0x3b, 0xae, 0xd8, 0xc5, 0xff, 0x2b, 0xe9, 0xe1, 0xa8, 0x36, 0xa5, 0xd6, 0x86, 0x6b, 0x87,
	0xac, 0xf3, 0xb8, 0xcf, 0xf1, 0x13, 0xa6, 0x9e, 0x9b, 0xc3, 0x04, 0xb5, 0xe9, 0x07, 0x4d, 0xbd,
	0x36, 0x92, 0x69, 0x52, 0x69, 0x5f, 0xc3, 0x1f, 0x32, 0xf5, 0xda, 0xc8, 0x96, 0x95, 0xd4, 0x87,
	0x4d, 0x72, 0xa6, 0xd8, 0x47, 0x83, 0x40, 0x7a, 0x68, 0xcd, 0xe5, 0x02, 0x7f, 0xc4, 0xd4, 0xf3,
	0x73, 0x08, 0x57, 0x7a, 0x3e, 0x6a, 0xea, 0x2e, 0xdc, 0xa0, 0xf6, 0x06, 0x84, 0xee, 0x96, 0x9b,
	0x4e, 0x33, 0x19, 0xaa, 0x8f, 0x99, 0x7a, 0x44, 0xa5, 0xe3, 0x9a, 0x7d, 0xe6, 0xc3, 0xb5, 0x68,
	0xb0, 0x09, 0xa1, 0xa4, 0x7d, 0xdc, 0xd4, 0xd3, 0x4c, 0xd2, 0x3a, 0x8f, 0xb1, 0x65, 0x1a, 0x17,
	0xa3, 0x24, 0x7d, 0xc2, 0x24, 0x73, 0xf9, 0xdc, 0x4e, 0x02, 0x6b, 0x79, 0xd4, 0x6f, 0x40, 0xac,
	0x28, 0x09, 0xfd, 0x27, 0x4d, 0xb2, 0x80, 0xce, 0xed, 0xc3, 0x50, 0xb6, 0x7f, 0xaa, 0x60, 0xbb,
	0xc5, 0x06, 0x41, 0x08, 0x9c, 0x83, 0xd3, 0xe0, 0xbd, 0x0e, 0x4b, 0x2b, 0x0c, 0x7f, 0xda, 0x24,
	0xf7, 0xa3, 0x7b, 0x34, 0x3f, 0x8c, 0x7f, 0x62, 0x66, 0xbd, 0xfb, 0x33, 0x26, 0xb9, 0x8c, 0x2e,
	0x1d, 0x50, 0x44, 0x9a, 0xf2, 0x59, 0x53, 0x2f, 0xf3, 0xf1, 0xef, 0xae, 0x6c, 0x8f, 0xcf, 0x99,
	0xe4, 0x5e, 0xb4, 0x78, 0x10, 0xbe, 0xdc, 0xe0, 0x49, 0x93, 0x5c, 0x41, 0xf7, 0x66, 0x02, 0x37,
	0x7b, 0xe0, 0x64, 0xdb, 0x7c, 0xde, 0x24, 0x0f, 0xa2, 0xfb, 0x0e, 0x2e, 0x25, 0x37, 0xfb, 0x82,
	0xb9, 0xf8, 0x37, 0x03, 0xdd, 0x5e, 0x6b, 0x5f, 0xcf, 0x1f, 0x3d, 0xc9, 0xff, 0xae, 0x15, 0x42,
	0x7c, 0x55, 0x98, 0x28, 0x2c, 0xa6, 0xf5, 0x8f, 0x4f, 0x92, 0x13, 0x49, 0x1e, 0xa7, 0x8b, 0x55,
	0xe0, 0x22, 0x64, 0xbb, 0x78, 0x52, 0xce, 0x49, 0x29, 0x1f, 0x0f, 0x87, 0x76, 0xb4, 0xc9, 0xed,
	0xd0, 0xdd, 0x04, 0x07, 0x97, 0xe5, 0xc3, 0x47, 0x43, 0xd7, 0x7d, 0x9e, 0xe3, 0x53, 0x72, 0xce,
	0xeb, 0x1b, 0x65, 0xc3, 0x1a, 0x4f, 0xcb, 0xbb, 0xc2, 0xb0, 0xea, 0x20, 0xbd, 0x8b, 0x6d, 0x85,
	0xc0, 0xfb, 0x78, 0x46, 0xce, 0xf3, 0x91, 0x16, 0xac, 0x07, 0x1d, 0x56, 0x8d, 0xad, 0x3f, 0xbd,
	0xf8, 0xeb, 0x43, 0x08, 0xd7, 0xea, 0x56, 0xdc, 0x33, 0x55, 0x7b, 0x96, 0x2d, 0x35, 0x69, 0x64,
	0xcd, 0xa4, 0x4f, 0xa7, 0x8e, 0xfd, 0xe1, 0xa4, 0x9c, 0xa5, 0x1a, 0x22, 0x9d, 0xf7, 0xa3, 0x49,
	0x59, 0x79, 0x09, 0x94, 0x25, 0x62, 0x93, 0x79, 0x9e, 0xc5, 0xfc, 0x1d, 0x1a, 0x66, 0x2a, 0x7e,
	0x3c, 0x29, 0x1b, 0xc4, 0x58, 0x9e, 0x54, 0xf8, 0x93, 0x49, 0xd9, 0x6c, 0x13, 0x62, 0x4a, 0xbb,
	0x01, 0x9e, 0xcd, 0x06, 0x80, 0x9f, 0x9e, 0xd5, 0xb1, 0x76, 0xf2, 0x52, 0xcb, 0xb0, 0x67, 0x66,
	0x75, 0xeb, 0x53, 0xb9, 0x15, 0xf0, 0x3c, 0x86, 0x9f, 0x2d, 0x20, 0xa9, 0x54, 0x8a, 0x3c, 0x37,
	0x2b, 0x6b, 0x58, 0x93, 0xb1, 0x98, 0xef, 0x43, 0xf2, 0x7e, 0x90, 0xa3, 0xe2, 0xf9, 0x02, 0x29,
	0x15, 0x1f, 0x22, 0xbd, 0x30, 0xbb, 0xf8, 0xfd, 0xdb, 0x11, 0xaa, 0xc5, 0x47, 0x4b, 0xb2, 0x4f,
	0x4d, 0x0c, 0xf9, 0x9d, 0xce, 0xc2, 0x8a, 0xbd, 0x8d, 0xbf, 0x68, 0xa8, 0x3a, 0xde, 0x8b, 0x29,
	0x27, 0x7c, 0x29, 0x9f, 0x8b, 0x92, 0x13, 0x4f, 0x4e, 0x70, 0xf0, 0x97, 0xf3, 0xab, 0x4b, 0x01,
	0x48, 0x1f, 0xdc, 0x5f, 0x31, 0x74, 0x53, 0xe5, 0xa0, 0x8a, 0x36, 0x63, 0xab, 0x93, 0x69, 0x15,
	0xbf, 0xff, 0xf0, 0x53, 0x86, 0x1c, 0x36, 0x09, 0x49, 0xc6, 0x67, 0x88, 0xf5, 0x55, 0x83, 0xdc,
	0x93, 0xdc, 0xd4, 0xf6, 0x63, 0x29, 0x7b, 0xbf, 0x96, 0xdf, 0x0f, 0x0a, 0x67, 0x4a, 0x5e, 0xdc,
	0x51, 0x10, 0x37, 0xab, 0xe4, 0x6e, 0xf5, 0xf5, 0xec, 0xde, 0x26, 0xb3, 0xa0, 0x6e, 0xb5, 0xaf,
	0x17, 0x53, 0x14, 0x7f, 0xa3, 0x70, 0x06, 0x8d, 0xa2, 0x55, 0x0a, 0xfe, 0xe6, 0x10, 0x69, 0x8d,
	0x51, 0x47, 0x5a, 0x26, 0xf9, 0xf8, 0x5b, 0xd9, 0x0d, 0x67, 0x1f, 0x92, 0x3a, 0xc1, 0xb7, 0x87,
	0x34, 0x16, 0xe6, 0x7c, 0x7a, 0x83, 0xfb, 0x8e, 0x21, 0xdb, 0x79, 0x4e, 0xf2, 0xdd, 0x1d, 0x08,
	0x39, 0xc8, 0x83, 0xe2, 0xef, 0x1a, 0xb2, 0x9d, 0x8f, 0x63, 0xa8, 0x0d, 0x9f, 0x36, 0x8a, 0x85,
	0x53, 0xb7, 0xe4, 0xf5, 0x77, 0xcf, 0x13, 0xe1, 0x19, 0xa3, 0x58, 0x38, 0x75, 0x2b, 0x75, 0xed,
	0xd5, 0x90, 0x51, 0xc7, 0xa6, 0x5c, 0x64, 0xef, 0xd3, 0x67, 0xc7, 0x10, 0x95, 0x6b, 0x3b, 0x2c,
	0xf5, 0xcb, 0x73, 0x86, 0xec, 0xc6, 0x37, 0x21, 0x2a, 0x53, 0xbf, 0x37, 0xe4, 0xc8, 0x54, 0x40,
	0x8b, 0x48, 0xfc, 0xe2, 0x4f, 0xb5, 0x3f, 0x3f, 0xe4, 0xc8, 0x94, 0x2c, 0x3b, 0x64, 0x4a, 0x7a,
	0xc1, 0xb8, 0x7a, 0x78, 0xc5, 0x78, 0xc2, 0xb8, 0xed, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x89,
	0x11, 0x0b, 0xca, 0x73, 0x16, 0x00, 0x00,
}
