// Code generated by protoc-gen-go. DO NOT EDIT.
// source: steamnetworkingsockets_messages_certs.proto

package dota

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CMsgSteamDatagramCertificate_EKeyType int32

const (
	CMsgSteamDatagramCertificate_INVALID CMsgSteamDatagramCertificate_EKeyType = 0
	CMsgSteamDatagramCertificate_ED25519 CMsgSteamDatagramCertificate_EKeyType = 1
)

var CMsgSteamDatagramCertificate_EKeyType_name = map[int32]string{
	0: "INVALID",
	1: "ED25519",
}

var CMsgSteamDatagramCertificate_EKeyType_value = map[string]int32{
	"INVALID": 0,
	"ED25519": 1,
}

func (x CMsgSteamDatagramCertificate_EKeyType) Enum() *CMsgSteamDatagramCertificate_EKeyType {
	p := new(CMsgSteamDatagramCertificate_EKeyType)
	*p = x
	return p
}

func (x CMsgSteamDatagramCertificate_EKeyType) String() string {
	return proto.EnumName(CMsgSteamDatagramCertificate_EKeyType_name, int32(x))
}

func (x *CMsgSteamDatagramCertificate_EKeyType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMsgSteamDatagramCertificate_EKeyType_value, data, "CMsgSteamDatagramCertificate_EKeyType")
	if err != nil {
		return err
	}
	*x = CMsgSteamDatagramCertificate_EKeyType(value)
	return nil
}

func (CMsgSteamDatagramCertificate_EKeyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a7ee927efd4d408d, []int{1, 0}
}

type CMsgSteamNetworkingIdentityLegacyBinary struct {
	SteamId              *uint64  `protobuf:"fixed64,16,opt,name=steam_id,json=steamId" json:"steam_id,omitempty"`
	XboxPairwiseId       *string  `protobuf:"bytes,17,opt,name=xbox_pairwise_id,json=xboxPairwiseId" json:"xbox_pairwise_id,omitempty"`
	GenericBytes         []byte   `protobuf:"bytes,2,opt,name=generic_bytes,json=genericBytes" json:"generic_bytes,omitempty"`
	GenericString        *string  `protobuf:"bytes,3,opt,name=generic_string,json=genericString" json:"generic_string,omitempty"`
	Ipv6AndPort          []byte   `protobuf:"bytes,4,opt,name=ipv6_and_port,json=ipv6AndPort" json:"ipv6_and_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgSteamNetworkingIdentityLegacyBinary) Reset() {
	*m = CMsgSteamNetworkingIdentityLegacyBinary{}
}
func (m *CMsgSteamNetworkingIdentityLegacyBinary) String() string { return proto.CompactTextString(m) }
func (*CMsgSteamNetworkingIdentityLegacyBinary) ProtoMessage()    {}
func (*CMsgSteamNetworkingIdentityLegacyBinary) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7ee927efd4d408d, []int{0}
}

func (m *CMsgSteamNetworkingIdentityLegacyBinary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgSteamNetworkingIdentityLegacyBinary.Unmarshal(m, b)
}
func (m *CMsgSteamNetworkingIdentityLegacyBinary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgSteamNetworkingIdentityLegacyBinary.Marshal(b, m, deterministic)
}
func (m *CMsgSteamNetworkingIdentityLegacyBinary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgSteamNetworkingIdentityLegacyBinary.Merge(m, src)
}
func (m *CMsgSteamNetworkingIdentityLegacyBinary) XXX_Size() int {
	return xxx_messageInfo_CMsgSteamNetworkingIdentityLegacyBinary.Size(m)
}
func (m *CMsgSteamNetworkingIdentityLegacyBinary) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgSteamNetworkingIdentityLegacyBinary.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgSteamNetworkingIdentityLegacyBinary proto.InternalMessageInfo

func (m *CMsgSteamNetworkingIdentityLegacyBinary) GetSteamId() uint64 {
	if m != nil && m.SteamId != nil {
		return *m.SteamId
	}
	return 0
}

func (m *CMsgSteamNetworkingIdentityLegacyBinary) GetXboxPairwiseId() string {
	if m != nil && m.XboxPairwiseId != nil {
		return *m.XboxPairwiseId
	}
	return ""
}

func (m *CMsgSteamNetworkingIdentityLegacyBinary) GetGenericBytes() []byte {
	if m != nil {
		return m.GenericBytes
	}
	return nil
}

func (m *CMsgSteamNetworkingIdentityLegacyBinary) GetGenericString() string {
	if m != nil && m.GenericString != nil {
		return *m.GenericString
	}
	return ""
}

func (m *CMsgSteamNetworkingIdentityLegacyBinary) GetIpv6AndPort() []byte {
	if m != nil {
		return m.Ipv6AndPort
	}
	return nil
}

type CMsgSteamDatagramCertificate struct {
	KeyType                 *CMsgSteamDatagramCertificate_EKeyType   `protobuf:"varint,1,opt,name=key_type,json=keyType,enum=dota.CMsgSteamDatagramCertificate_EKeyType,def=0" json:"key_type,omitempty"`
	KeyData                 []byte                                   `protobuf:"bytes,2,opt,name=key_data,json=keyData" json:"key_data,omitempty"`
	LegacySteamId           *uint64                                  `protobuf:"fixed64,4,opt,name=legacy_steam_id,json=legacySteamId" json:"legacy_steam_id,omitempty"`
	LegacyIdentityBinary    *CMsgSteamNetworkingIdentityLegacyBinary `protobuf:"bytes,11,opt,name=legacy_identity_binary,json=legacyIdentityBinary" json:"legacy_identity_binary,omitempty"`
	IdentityString          *string                                  `protobuf:"bytes,12,opt,name=identity_string,json=identityString" json:"identity_string,omitempty"`
	GameserverDatacenterIds []uint32                                 `protobuf:"fixed32,5,rep,name=gameserver_datacenter_ids,json=gameserverDatacenterIds" json:"gameserver_datacenter_ids,omitempty"`
	TimeCreated             *uint32                                  `protobuf:"fixed32,8,opt,name=time_created,json=timeCreated" json:"time_created,omitempty"`
	TimeExpiry              *uint32                                  `protobuf:"fixed32,9,opt,name=time_expiry,json=timeExpiry" json:"time_expiry,omitempty"`
	AppIds                  []uint32                                 `protobuf:"varint,10,rep,name=app_ids,json=appIds" json:"app_ids,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                                 `json:"-"`
	XXX_unrecognized        []byte                                   `json:"-"`
	XXX_sizecache           int32                                    `json:"-"`
}

func (m *CMsgSteamDatagramCertificate) Reset()         { *m = CMsgSteamDatagramCertificate{} }
func (m *CMsgSteamDatagramCertificate) String() string { return proto.CompactTextString(m) }
func (*CMsgSteamDatagramCertificate) ProtoMessage()    {}
func (*CMsgSteamDatagramCertificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7ee927efd4d408d, []int{1}
}

func (m *CMsgSteamDatagramCertificate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgSteamDatagramCertificate.Unmarshal(m, b)
}
func (m *CMsgSteamDatagramCertificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgSteamDatagramCertificate.Marshal(b, m, deterministic)
}
func (m *CMsgSteamDatagramCertificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgSteamDatagramCertificate.Merge(m, src)
}
func (m *CMsgSteamDatagramCertificate) XXX_Size() int {
	return xxx_messageInfo_CMsgSteamDatagramCertificate.Size(m)
}
func (m *CMsgSteamDatagramCertificate) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgSteamDatagramCertificate.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgSteamDatagramCertificate proto.InternalMessageInfo

const Default_CMsgSteamDatagramCertificate_KeyType CMsgSteamDatagramCertificate_EKeyType = CMsgSteamDatagramCertificate_INVALID

func (m *CMsgSteamDatagramCertificate) GetKeyType() CMsgSteamDatagramCertificate_EKeyType {
	if m != nil && m.KeyType != nil {
		return *m.KeyType
	}
	return Default_CMsgSteamDatagramCertificate_KeyType
}

func (m *CMsgSteamDatagramCertificate) GetKeyData() []byte {
	if m != nil {
		return m.KeyData
	}
	return nil
}

func (m *CMsgSteamDatagramCertificate) GetLegacySteamId() uint64 {
	if m != nil && m.LegacySteamId != nil {
		return *m.LegacySteamId
	}
	return 0
}

func (m *CMsgSteamDatagramCertificate) GetLegacyIdentityBinary() *CMsgSteamNetworkingIdentityLegacyBinary {
	if m != nil {
		return m.LegacyIdentityBinary
	}
	return nil
}

func (m *CMsgSteamDatagramCertificate) GetIdentityString() string {
	if m != nil && m.IdentityString != nil {
		return *m.IdentityString
	}
	return ""
}

func (m *CMsgSteamDatagramCertificate) GetGameserverDatacenterIds() []uint32 {
	if m != nil {
		return m.GameserverDatacenterIds
	}
	return nil
}

func (m *CMsgSteamDatagramCertificate) GetTimeCreated() uint32 {
	if m != nil && m.TimeCreated != nil {
		return *m.TimeCreated
	}
	return 0
}

func (m *CMsgSteamDatagramCertificate) GetTimeExpiry() uint32 {
	if m != nil && m.TimeExpiry != nil {
		return *m.TimeExpiry
	}
	return 0
}

func (m *CMsgSteamDatagramCertificate) GetAppIds() []uint32 {
	if m != nil {
		return m.AppIds
	}
	return nil
}

type CMsgSteamDatagramCertificateSigned struct {
	Cert                 []byte   `protobuf:"bytes,4,opt,name=cert" json:"cert,omitempty"`
	CaKeyId              *uint64  `protobuf:"fixed64,5,opt,name=ca_key_id,json=caKeyId" json:"ca_key_id,omitempty"`
	CaSignature          []byte   `protobuf:"bytes,6,opt,name=ca_signature,json=caSignature" json:"ca_signature,omitempty"`
	PrivateKeyData       []byte   `protobuf:"bytes,1,opt,name=private_key_data,json=privateKeyData" json:"private_key_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgSteamDatagramCertificateSigned) Reset()         { *m = CMsgSteamDatagramCertificateSigned{} }
func (m *CMsgSteamDatagramCertificateSigned) String() string { return proto.CompactTextString(m) }
func (*CMsgSteamDatagramCertificateSigned) ProtoMessage()    {}
func (*CMsgSteamDatagramCertificateSigned) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7ee927efd4d408d, []int{2}
}

func (m *CMsgSteamDatagramCertificateSigned) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgSteamDatagramCertificateSigned.Unmarshal(m, b)
}
func (m *CMsgSteamDatagramCertificateSigned) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgSteamDatagramCertificateSigned.Marshal(b, m, deterministic)
}
func (m *CMsgSteamDatagramCertificateSigned) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgSteamDatagramCertificateSigned.Merge(m, src)
}
func (m *CMsgSteamDatagramCertificateSigned) XXX_Size() int {
	return xxx_messageInfo_CMsgSteamDatagramCertificateSigned.Size(m)
}
func (m *CMsgSteamDatagramCertificateSigned) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgSteamDatagramCertificateSigned.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgSteamDatagramCertificateSigned proto.InternalMessageInfo

func (m *CMsgSteamDatagramCertificateSigned) GetCert() []byte {
	if m != nil {
		return m.Cert
	}
	return nil
}

func (m *CMsgSteamDatagramCertificateSigned) GetCaKeyId() uint64 {
	if m != nil && m.CaKeyId != nil {
		return *m.CaKeyId
	}
	return 0
}

func (m *CMsgSteamDatagramCertificateSigned) GetCaSignature() []byte {
	if m != nil {
		return m.CaSignature
	}
	return nil
}

func (m *CMsgSteamDatagramCertificateSigned) GetPrivateKeyData() []byte {
	if m != nil {
		return m.PrivateKeyData
	}
	return nil
}

type CMsgSteamDatagramCertificateRequest struct {
	Cert                 *CMsgSteamDatagramCertificate `protobuf:"bytes,1,opt,name=cert" json:"cert,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *CMsgSteamDatagramCertificateRequest) Reset()         { *m = CMsgSteamDatagramCertificateRequest{} }
func (m *CMsgSteamDatagramCertificateRequest) String() string { return proto.CompactTextString(m) }
func (*CMsgSteamDatagramCertificateRequest) ProtoMessage()    {}
func (*CMsgSteamDatagramCertificateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7ee927efd4d408d, []int{3}
}

func (m *CMsgSteamDatagramCertificateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgSteamDatagramCertificateRequest.Unmarshal(m, b)
}
func (m *CMsgSteamDatagramCertificateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgSteamDatagramCertificateRequest.Marshal(b, m, deterministic)
}
func (m *CMsgSteamDatagramCertificateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgSteamDatagramCertificateRequest.Merge(m, src)
}
func (m *CMsgSteamDatagramCertificateRequest) XXX_Size() int {
	return xxx_messageInfo_CMsgSteamDatagramCertificateRequest.Size(m)
}
func (m *CMsgSteamDatagramCertificateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgSteamDatagramCertificateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgSteamDatagramCertificateRequest proto.InternalMessageInfo

func (m *CMsgSteamDatagramCertificateRequest) GetCert() *CMsgSteamDatagramCertificate {
	if m != nil {
		return m.Cert
	}
	return nil
}

func init() {
	proto.RegisterEnum("dota.CMsgSteamDatagramCertificate_EKeyType", CMsgSteamDatagramCertificate_EKeyType_name, CMsgSteamDatagramCertificate_EKeyType_value)
	proto.RegisterType((*CMsgSteamNetworkingIdentityLegacyBinary)(nil), "dota.CMsgSteamNetworkingIdentityLegacyBinary")
	proto.RegisterType((*CMsgSteamDatagramCertificate)(nil), "dota.CMsgSteamDatagramCertificate")
	proto.RegisterType((*CMsgSteamDatagramCertificateSigned)(nil), "dota.CMsgSteamDatagramCertificateSigned")
	proto.RegisterType((*CMsgSteamDatagramCertificateRequest)(nil), "dota.CMsgSteamDatagramCertificateRequest")
}

func init() {
	proto.RegisterFile("steamnetworkingsockets_messages_certs.proto", fileDescriptor_a7ee927efd4d408d)
}

var fileDescriptor_a7ee927efd4d408d = []byte{
	// 595 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0x5d, 0x6f, 0xd3, 0x3e,
	0x14, 0xc6, 0xe7, 0x7f, 0xbb, 0xb5, 0x3b, 0x7d, 0x59, 0xff, 0x16, 0x62, 0x19, 0x42, 0x22, 0x64,
	0xc0, 0x22, 0x4d, 0x54, 0x62, 0xd2, 0x26, 0xb1, 0xbb, 0x6d, 0x9d, 0x44, 0xb4, 0x31, 0xa6, 0x14,
	0x71, 0x87, 0x2c, 0x2f, 0x3e, 0x44, 0x56, 0x69, 0x12, 0x6c, 0xef, 0x25, 0x77, 0x7c, 0x15, 0xbe,
	0x18, 0x5f, 0x05, 0x64, 0xe7, 0x05, 0x89, 0x8b, 0x72, 0x17, 0xff, 0x7c, 0x7c, 0xe2, 0xf3, 0x3c,
	0x8f, 0x61, 0x5f, 0x1b, 0xe4, 0xcb, 0x0c, 0xcd, 0x7d, 0xae, 0x16, 0x32, 0x4b, 0x75, 0x9e, 0x2c,
	0xd0, 0x68, 0xb6, 0x44, 0xad, 0x79, 0x8a, 0x9a, 0x25, 0xa8, 0x8c, 0x9e, 0x16, 0x2a, 0x37, 0x39,
	0xed, 0x8a, 0xdc, 0xf0, 0xe0, 0x27, 0x81, 0xbd, 0xb3, 0xf7, 0x3a, 0x9d, 0xdb, 0x93, 0x57, 0xed,
	0xc9, 0x48, 0x60, 0x66, 0xa4, 0x29, 0x2f, 0x31, 0xe5, 0x49, 0x79, 0x2a, 0x33, 0xae, 0x4a, 0xba,
	0x03, 0x7d, 0xf7, 0x03, 0x26, 0x85, 0x37, 0xf1, 0x49, 0xb8, 0x11, 0xf7, 0xdc, 0x3a, 0x12, 0x34,
	0x84, 0xc9, 0xc3, 0x4d, 0xfe, 0xc0, 0x0a, 0x2e, 0xd5, 0xbd, 0xd4, 0x68, 0x4b, 0xfe, 0xf7, 0x49,
	0xb8, 0x19, 0x8f, 0x2d, 0xbf, 0xae, 0x71, 0x24, 0xe8, 0x2e, 0x8c, 0x52, 0xcc, 0x50, 0xc9, 0x84,
	0xdd, 0x94, 0x06, 0xb5, 0xf7, 0x9f, 0x4f, 0xc2, 0x61, 0x3c, 0xac, 0xe1, 0xa9, 0x65, 0xf4, 0x25,
	0x8c, 0x9b, 0x22, 0x6d, 0x94, 0xcc, 0x52, 0xaf, 0xe3, 0x9a, 0x35, 0x47, 0xe7, 0x0e, 0xd2, 0x00,
	0x46, 0xb2, 0xb8, 0x3b, 0x62, 0x3c, 0x13, 0xac, 0xc8, 0x95, 0xf1, 0xba, 0xae, 0xd7, 0xc0, 0xc2,
	0x93, 0x4c, 0x5c, 0xe7, 0xca, 0x04, 0xbf, 0x3a, 0xf0, 0xb4, 0x1d, 0x70, 0xc6, 0x0d, 0x4f, 0x15,
	0x5f, 0x9e, 0xa1, 0x32, 0xf2, 0x8b, 0x4c, 0xb8, 0x41, 0xfa, 0x01, 0xfa, 0x0b, 0x2c, 0x99, 0x29,
	0x0b, 0xf4, 0x88, 0x4f, 0xc2, 0xf1, 0xc1, 0xfe, 0xd4, 0x4a, 0x33, 0x5d, 0x75, 0x6a, 0x7a, 0x7e,
	0x81, 0xe5, 0xc7, 0xb2, 0xc0, 0xe3, 0x5e, 0x74, 0xf5, 0xe9, 0xe4, 0x32, 0x9a, 0xc5, 0xbd, 0x45,
	0x45, 0xac, 0x4c, 0xb6, 0xa1, 0xe0, 0x86, 0xd7, 0xc3, 0xd9, 0x2d, 0xdb, 0x84, 0xbe, 0x82, 0xad,
	0xaf, 0x4e, 0x51, 0xd6, 0x0a, 0xd9, 0x75, 0x42, 0x8e, 0x2a, 0x3c, 0xaf, 0xe5, 0x4c, 0xe0, 0x71,
	0x5d, 0x27, 0x6b, 0x23, 0xd8, 0x8d, 0xf3, 0xc0, 0x1b, 0xf8, 0x24, 0x1c, 0x1c, 0xbc, 0xfe, 0xeb,
	0x86, 0xab, 0x8d, 0x8b, 0x1f, 0x55, 0xcd, 0x9a, 0xbd, 0xda, 0xce, 0x3d, 0xd8, 0x6a, 0xbb, 0xd7,
	0x2a, 0x0f, 0x2b, 0xcb, 0x1a, 0x5c, 0xcb, 0x7c, 0x0c, 0x3b, 0x29, 0x5f, 0xa2, 0x46, 0x75, 0x87,
	0xca, 0xcd, 0x95, 0x60, 0x66, 0x50, 0x31, 0x29, 0xb4, 0xb7, 0xee, 0x77, 0xc2, 0x5e, 0xbc, 0xfd,
	0xa7, 0x60, 0xd6, 0xee, 0x47, 0x42, 0xd3, 0xe7, 0x30, 0x34, 0x72, 0x89, 0x2c, 0x51, 0xc8, 0x0d,
	0x0a, 0xaf, 0xef, 0x93, 0xb0, 0x17, 0x0f, 0x2c, 0x3b, 0xab, 0x10, 0x7d, 0x06, 0x6e, 0xc9, 0xf0,
	0xa1, 0x90, 0xaa, 0xf4, 0x36, 0x5d, 0x05, 0x58, 0x74, 0xee, 0x08, 0xdd, 0x86, 0x1e, 0x2f, 0x0a,
	0xf7, 0x37, 0xf0, 0x3b, 0xe1, 0x28, 0xde, 0xe0, 0x45, 0x11, 0x09, 0x1d, 0xbc, 0x80, 0x7e, 0xe3,
	0x03, 0x1d, 0x40, 0xe3, 0xc4, 0x64, 0xcd, 0x2e, 0xce, 0x67, 0x07, 0x87, 0x87, 0x6f, 0xde, 0x4e,
	0x48, 0xf0, 0x83, 0x40, 0xb0, 0xca, 0xcb, 0xb9, 0x4c, 0x33, 0x14, 0x94, 0x42, 0xd7, 0x3e, 0x8f,
	0x3a, 0x43, 0xee, 0x9b, 0x3e, 0x81, 0xcd, 0x84, 0x33, 0xeb, 0xa6, 0x14, 0xde, 0x7a, 0x15, 0xf9,
	0x84, 0x5f, 0x60, 0x19, 0x09, 0x3b, 0x59, 0xc2, 0x99, 0x96, 0x69, 0xc6, 0xcd, 0xad, 0x42, 0x6f,
	0xa3, 0xca, 0x5e, 0xc2, 0xe7, 0x0d, 0xb2, 0xaf, 0xa2, 0x50, 0xf2, 0x8e, 0x1b, 0x64, 0x6d, 0x22,
	0x88, 0x2b, 0x1b, 0xd7, 0xfc, 0xa2, 0x0a, 0x46, 0xf0, 0x19, 0x76, 0x57, 0x5d, 0x31, 0xc6, 0x6f,
	0xb7, 0xa8, 0x0d, 0x3d, 0xaa, 0xef, 0x48, 0x5c, 0x0a, 0x82, 0x7f, 0xe7, 0xb4, 0x9a, 0xe3, 0x74,
	0xfd, 0x1d, 0xf9, 0x4e, 0xd6, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x97, 0xba, 0x95, 0x4c, 0x20,
	0x04, 0x00, 0x00,
}
