syntax = "proto2";

package dota;
option go_package = "github.com/dotabuff/manta/dota;dota";

import "steammessages_unified_base.steamworkssdk.proto";

message COAuthToken_ImplicitGrantNoPrompt_Request {
	optional string clientid = 1;
}

message COAuthToken_ImplicitGrantNoPrompt_Response {
	optional string access_token = 1;
	optional string redirect_uri = 2;
}

service OAuthToken {

	rpc ImplicitGrantNoPrompt (COAuthToken_ImplicitGrantNoPrompt_Request) returns (COAuthToken_ImplicitGrantNoPrompt_Response) {
	}
}
