name: CI
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3

      - name: cache replays
        uses: actions/cache@v2
        with:
          path: '**/replays'
          key: replays

      - name: get dependencies
        run: go mod download

      - name: run tests
        run: make test

